/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.MovimientosAlmacen;

import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import C.MovimientosAlmacen.movimientosalmacen;
import Frames.Listados.ListarAlmacenes;
import Frames.Listados.ListarAnaqueles;
import Frames.Listados.ListarBins;
import Frames.Listados.ListarPasillos;
import Frames.Listados.ListarProductos;
import Frames.Menu;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jraraujo
 */
public class MovimientosAlmacen extends javax.swing.JFrame {

    Instancias inst = new Instancias();
    movimientosalmacen mov = new movimientosalmacen();
    JTextAreaMessages jtm = new JTextAreaMessages();
    String whoisselected;
    CheckAccess chk = new CheckAccess();
    JTableHeader th;
    /**
     * Creates new form MovimientosAlmacen
     */
    public MovimientosAlmacen() {
        initComponents();
        this.setLocationRelativeTo(null);
        jtmovimientos.setDefaultEditor(Object.class, null);
        th = jtmovimientos.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        chk.revisarAccesosMovimientosAlmacen(Menu.idusu);
        mov.mostrarUbicacionProductos(jtmovimientos, "", Menu.idcompania);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jtxtbproducto = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbsalir = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jbproducto = new javax.swing.JButton();
        jtxtidproducto = new javax.swing.JTextField();
        jtxtproducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtdescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jtxtunidad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbalmacen = new javax.swing.JButton();
        jbpasillo = new javax.swing.JButton();
        jbanaquel = new javax.swing.JButton();
        jbbin = new javax.swing.JButton();
        jtxtidalmacen = new javax.swing.JTextField();
        jtxtidpasillo = new javax.swing.JTextField();
        jtxtidanaquel = new javax.swing.JTextField();
        jtxtidbin = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jborigen_almacen = new javax.swing.JButton();
        jtxtorialmacen = new javax.swing.JTextField();
        jborigen_pasillo = new javax.swing.JButton();
        jtxtoripasillo = new javax.swing.JTextField();
        jborigen_anaquel = new javax.swing.JButton();
        jborigen_bin = new javax.swing.JButton();
        jtxtorianaquel = new javax.swing.JTextField();
        jtxtoribin = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtmovimientos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmacciones = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmreporte = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Moviemientos al Almacen]");
        setIconImage(getIconImage());

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setEnabled(false);
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator1);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setEnabled(false);
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator2);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setEnabled(false);
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator5);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setBorder(null);
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setEnabled(false);
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator6);

        jLabel1.setText("Buscar producto:");
        jToolBar1.add(jLabel1);

        jtxtbproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbproductoKeyReleased(evt);
            }
        });
        jToolBar1.add(jtxtbproducto);
        jToolBar1.add(jSeparator3);

        jbsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jbsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsalirMouseClicked(evt);
            }
        });
        jToolBar1.add(jbsalir);
        jToolBar1.add(jSeparator8);

        jPanel2.setBackground(Color.decode("#C70039")
        );

        jPanel3.setOpaque(false);

        jbproducto.setText("Producto:");
        jbproducto.setEnabled(false);
        jbproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbproductoActionPerformed(evt);
            }
        });

        jtxtidproducto.setEditable(false);

        jtxtproducto.setEditable(false);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Producto:");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        jtxtdescripcion.setEditable(false);
        jtxtdescripcion.setColumns(20);
        jtxtdescripcion.setRows(5);
        jScrollPane2.setViewportView(jtxtdescripcion);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Unidad:");

        jtxtunidad.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtxtidproducto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtunidad)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbproducto)
                    .addComponent(jtxtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Destino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        jbalmacen.setText("Almacen:");
        jbalmacen.setEnabled(false);
        jbalmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbalmacenActionPerformed(evt);
            }
        });

        jbpasillo.setText("Pasillo:");
        jbpasillo.setEnabled(false);
        jbpasillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpasilloActionPerformed(evt);
            }
        });

        jbanaquel.setText("Anaquel:");
        jbanaquel.setEnabled(false);
        jbanaquel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbanaquelActionPerformed(evt);
            }
        });

        jbbin.setText("Bin:");
        jbbin.setEnabled(false);
        jbbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbinActionPerformed(evt);
            }
        });

        jtxtidalmacen.setEditable(false);

        jtxtidpasillo.setEditable(false);

        jtxtidanaquel.setEditable(false);

        jtxtidbin.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbalmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jbpasillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbanaquel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbbin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtidpasillo)
                    .addComponent(jtxtidanaquel)
                    .addComponent(jtxtidbin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jtxtidalmacen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbalmacen)
                    .addComponent(jtxtidalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbpasillo)
                    .addComponent(jtxtidpasillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbanaquel)
                    .addComponent(jtxtidanaquel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbbin)
                    .addComponent(jtxtidbin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Origen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        jborigen_almacen.setText("Almacen:");
        jborigen_almacen.setEnabled(false);
        jborigen_almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jborigen_almacenActionPerformed(evt);
            }
        });

        jborigen_pasillo.setText("Pasillo:");
        jborigen_pasillo.setEnabled(false);
        jborigen_pasillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jborigen_pasilloActionPerformed(evt);
            }
        });

        jborigen_anaquel.setText("Anaquel:");
        jborigen_anaquel.setEnabled(false);
        jborigen_anaquel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jborigen_anaquelActionPerformed(evt);
            }
        });

        jborigen_bin.setText("Bin:");
        jborigen_bin.setEnabled(false);
        jborigen_bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jborigen_binActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jborigen_bin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jborigen_anaquel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jborigen_pasillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jborigen_almacen, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtorialmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jtxtoripasillo)
                    .addComponent(jtxtorianaquel)
                    .addComponent(jtxtoribin))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jborigen_almacen)
                    .addComponent(jtxtorialmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jborigen_pasillo)
                    .addComponent(jtxtoripasillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jborigen_anaquel)
                    .addComponent(jtxtorianaquel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jborigen_bin)
                    .addComponent(jtxtoribin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Traspasos de Almacen", jPanel2);

        jtmovimientos.setAutoCreateRowSorter(true);
        jtmovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtmovimientos.setForeground(new java.awt.Color(0, 102, 102));
        jtmovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Entrada", "Id Compra", "Id Almacen", "Id Pasillo", "Id Anaquel", "Id Bin", "Id Producto", "Producto", "Cantidad", "Id Empleado", "Id Empresa"
            }
        ));
        jScrollPane1.setViewportView(jtmovimientos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(Color.decode("#C70039")
        );

        jmacciones.setForeground(new java.awt.Color(255, 255, 255));
        jmacciones.setText("Acciones");
        jmacciones.setEnabled(false);

        jmi_guardar.setText("Guardar");
        jmi_guardar.setEnabled(false);
        jmacciones.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.setEnabled(false);
        jmacciones.add(jmi_cancelar);

        jmi_exportar.setText("Exportar");
        jmi_exportar.setEnabled(false);
        jmacciones.add(jmi_exportar);
        jmacciones.add(jSeparator7);

        jMenuItem4.setText("Salir");
        jmacciones.add(jMenuItem4);

        jMenuBar1.add(jmacciones);

        jmreporte.setForeground(new java.awt.Color(255, 255, 255));
        jmreporte.setText("Reporte");
        jmreporte.setEnabled(false);

        jMenuItem1.setText("Reporte");
        jMenuItem1.setEnabled(false);
        jmreporte.add(jMenuItem1);

        jMenuBar1.add(jmreporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbsalirMouseClicked

        Instancias._movimientosalmacen = null;
        this.dispose();
        
    }//GEN-LAST:event_jbsalirMouseClicked

    private void jbproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproductoActionPerformed

        whoisselected = "movimientosproducto";
        ListarProductos.whoisselected = whoisselected;
        inst.getInstanciasListarProductos();
        
    }//GEN-LAST:event_jbproductoActionPerformed

    private void jbalmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbalmacenActionPerformed

        whoisselected = "movimientosalmacen";
        ListarAlmacenes.whoisselected = whoisselected;
        inst.getInstanciasListarAlmacenes();
        
    }//GEN-LAST:event_jbalmacenActionPerformed

    private void jbpasilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpasilloActionPerformed

        whoisselected = "movimientospasillo";
        ListarPasillos.whoisselected = whoisselected;
        inst.getInstanciasListarPasillos();
        
    }//GEN-LAST:event_jbpasilloActionPerformed

    private void jbanaquelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbanaquelActionPerformed

        whoisselected = "movimientosanaquel";
        ListarAnaqueles.whoisselected = whoisselected;
        inst.getInstanciasListarAnaqueles();
        
    }//GEN-LAST:event_jbanaquelActionPerformed

    private void jbbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbinActionPerformed

        whoisselected = "movimientosbin";
        ListarBins.whoisselected = whoisselected;
        inst.getInstanciasListarBin();
        
    }//GEN-LAST:event_jbbinActionPerformed

    private void jtxtbproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbproductoKeyReleased

        mov.mostrarUbicacionProductos(jtmovimientos, jtxtbproducto.getText(), Menu.idcompania);
        
    }//GEN-LAST:event_jtxtbproductoKeyReleased

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        if(jtxtidalmacen.getText().equals("") ||
                jtxtidpasillo.getText().equals("") ||
                jtxtidanaquel.getText().equals("") ||
                jtxtidbin.getText().equals("") ||
                jtxtidproducto.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            mov.jbguardar(Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()), 
                    Integer.parseInt(jtxtidproducto.getText()), 
                    Menu.idusu,
                    Menu.idcompania);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        mov.jbcancelar(jtxtidproducto, jtxtproducto, jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
        mov.mostrarUbicacionProductos(jtmovimientos, "", Menu.idcompania);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtmovimientos);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jborigen_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jborigen_almacenActionPerformed

        if(jtxtidproducto.getText().equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un producto");
        }else{
            whoisselected = "origen_almacen";
            ListarAlmacenes.whoisselected = whoisselected;
            inst.getInstanciasListarAlmacenes();
        }
        
    }//GEN-LAST:event_jborigen_almacenActionPerformed

    private void jborigen_pasilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jborigen_pasilloActionPerformed

        if(jtxtorialmacen.getText().equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un almacen");
        }else{
            whoisselected = "origen_pasillo";
            ListarPasillos.whoisselected = whoisselected;
            inst.getInstanciasListarPasillos();
        }
        
    }//GEN-LAST:event_jborigen_pasilloActionPerformed

    private void jborigen_anaquelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jborigen_anaquelActionPerformed

        if(jtxtoripasillo.getText().equals("")){
            jtm.jTextAreaMessage("No se ha selecccionado un pasillo");
        }else{
            whoisselected = "origen_anaquel";
            ListarAnaqueles.whoisselected = whoisselected;
            inst.getInstanciasListarAnaqueles();
        }
        
    }//GEN-LAST:event_jborigen_anaquelActionPerformed

    private void jborigen_binActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jborigen_binActionPerformed
        if(jtxtorianaquel.getText().equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un anaquel");
        }else{
            whoisselected = "origen_bin";
            ListarBins.whoisselected = whoisselected;
            inst.getInstanciasListarBin();
        }
    }//GEN-LAST:event_jborigen_binActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientosAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MovimientosAlmacen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbalmacen;
    public static javax.swing.JButton jbanaquel;
    public static javax.swing.JButton jbbin;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jborigen_almacen;
    public static javax.swing.JButton jborigen_anaquel;
    public static javax.swing.JButton jborigen_bin;
    public static javax.swing.JButton jborigen_pasillo;
    public static javax.swing.JButton jbpasillo;
    public static javax.swing.JButton jbproducto;
    public static javax.swing.JButton jbreporte;
    private javax.swing.JLabel jbsalir;
    public static javax.swing.JMenu jmacciones;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenu jmreporte;
    private javax.swing.JTable jtmovimientos;
    private javax.swing.JTextField jtxtbproducto;
    public static javax.swing.JTextArea jtxtdescripcion;
    public static javax.swing.JTextField jtxtidalmacen;
    public static javax.swing.JTextField jtxtidanaquel;
    public static javax.swing.JTextField jtxtidbin;
    public static javax.swing.JTextField jtxtidpasillo;
    public static javax.swing.JTextField jtxtidproducto;
    public static javax.swing.JTextField jtxtorialmacen;
    public static javax.swing.JTextField jtxtorianaquel;
    public static javax.swing.JTextField jtxtoribin;
    public static javax.swing.JTextField jtxtoripasillo;
    public static javax.swing.JTextField jtxtproducto;
    public static javax.swing.JTextField jtxtunidad;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    } 

}
