/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Caja;

import C.Caja.caja;
import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import Frames.Menu;
import ReportesJasper.reportes;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author jraraujo
 */
public class Caja extends javax.swing.JFrame {

    Border border, margin;
    String fecha;
    int idcaja;
    double caja;
    File archivo;
    Timer timer;
    JFileChooser SelectArchivo;  
    caja ca = new caja();
    JTextAreaMessages jtm = new JTextAreaMessages();
    reportes rep = new reportes();
    Image img;
    CheckAccess chk = new CheckAccess();
    JTableHeader th;
    
    /**
     * Creates new form Corte
     */
    public Caja() {
        initComponents();    
        jtcaja.setDefaultEditor(Object.class, null);
        th = jtcaja.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        chk.revisarAccesosCaja(Menu.idusu);
        ca.muestraRegistros(jtcaja, Menu.idcompania);
        timer = new Timer(1000, new cronometro());
        timer.start(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jbmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbsalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtcaja = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtcaja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtidusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtfechaactual = new javax.swing.JTextField();
        jdcfecha = new com.toedter.calendar.JDateChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmacciones = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmreporte = new javax.swing.JMenu();
        jmireporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fenix POS[Caja]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setBounds(0, 0, 50, 35);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setEnabled(false);
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator5);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setEnabled(false);
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator6);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setEnabled(false);
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator4);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setBorder(null);
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.setEnabled(false);
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator3);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setEnabled(false);
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator2);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setBorder(null);
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setEnabled(false);
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator1);

        jbsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jbsalir.setBorder(null);
        jbsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbsalir.setFocusable(false);
        jbsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbsalir);

        jPanel3.setBackground(Color.decode("#C70039"));
        jPanel3.setOpaque(false);

        jtcaja.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), Color.decode("#C70039"))); // NOI18N
        jtcaja.setForeground(new java.awt.Color(0, 153, 153));
        jtcaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Caja", "Fecha de Registro", "Id Empledo", "Id Empresa"
            }
        ));
        jtcaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtcajaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtcaja);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(Color.decode("#C70039"));

        jPanel1.setBackground(Color.decode("#C70039"));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Caja:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Empleado:");

        jtxtidusuario.setEditable(false);
        jtxtidusuario.setText(String.valueOf(Menu.idusu));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha actual:");

        jtxtfechaactual.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtfechaactual)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtcaja, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtidusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtcaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtfechaactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);

        jTabbedPane1.addTab("Registro de Caja", jPanel2);

        jMenuBar2.setBackground(Color.decode("#A80030")
        );

        jmacciones.setForeground(new java.awt.Color(255, 255, 255));
        jmacciones.setText("Acciones");
        jmacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmacciones.setEnabled(false);

        jmi_guardar.setText("Guardar");
        jmi_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_guardar.setEnabled(false);
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_cancelar.setEnabled(false);
        jmi_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cancelarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_cancelar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_eliminar.setEnabled(false);
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_eliminar);

        jmi_modificar.setText("Modificar");
        jmi_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_modificar.setEnabled(false);
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_modificar);

        jmi_exportar.setText("Exportar");
        jmi_exportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_exportar.setEnabled(false);
        jmi_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_exportarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_exportar);
        jmacciones.add(jSeparator7);

        jMenuItem1.setText("Salir");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmacciones.add(jMenuItem1);

        jMenuBar2.add(jmacciones);

        jmreporte.setForeground(new java.awt.Color(255, 255, 255));
        jmreporte.setText("Reportes");
        jmreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmreporte.setEnabled(false);

        jmireporte.setText("Reporte");
        jmireporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmireporte.setEnabled(false);
        jmireporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmireporteActionPerformed(evt);
            }
        });
        jmreporte.add(jmireporte);

        jMenuBar2.add(jmreporte);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed

        Instancias._caja = null;
        this.dispose();

    }//GEN-LAST:event_jbsalirActionPerformed

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed

         if(jtxtcaja.getText().equals("") || jtxtfechaactual.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            ca.jbguardar(Double.parseDouble(jtxtcaja.getText()), 
                    jtxtfechaactual.getText(), 
                    Integer.parseInt(jtxtidusuario.getText()),
                    Menu.idcompania);
            ca.jbcancelar(jtxtcaja);
            ca.muestraRegistros(jtcaja, Menu.idcompania);
        }

    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jmi_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cancelarActionPerformed

         ca.jbcancelar(jtxtcaja);
         ca.muestraRegistros(jtcaja, Menu.idcompania);

    }//GEN-LAST:event_jmi_cancelarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed

       if(String.valueOf(idcaja).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado caja");
        }else{
            ca.jbeliminar(idcaja, Menu.idcompania);
            ca.jbcancelar(jtxtcaja);
            ca.muestraRegistros(jtcaja, Menu.idcompania);
        }

    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed

       if(String.valueOf(idcaja).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado caja");
        }else{
            ca.jbmodificar(Double.parseDouble(jtxtcaja.getText()), 
                    jtxtfechaactual.getText(), 
                        Integer.parseInt(jtxtidusuario.getText()), 
                        Menu.idcompania,
                        idcaja);
            ca.muestraRegistros(jtcaja, Menu.idcompania);
            ca.jbcancelar(jtxtcaja);
        }

    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jmi_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_exportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtcaja);

    }//GEN-LAST:event_jmi_exportarActionPerformed

    private void jtcajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtcajaMouseClicked

        try {
            idcaja = Integer.parseInt(jtcaja.getValueAt(jtcaja.getSelectedRow(), 0).toString());
            jtxtcaja.setText(jtcaja.getValueAt(jtcaja.getSelectedRow(), 1).toString());
            fecha = jtcaja.getValueAt(jtcaja.getSelectedRow(), 2).toString();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date date = df.parse(fecha);
            jdcfecha.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Caja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jtcajaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._caja = null;
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jmireporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmireporteActionPerformed

         try {
            rep.EmisionReporteDeCaja("/ReportesJasper/", "ReporteCaja.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Caja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmireporteActionPerformed

    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed

        try {
            rep.EmisionReporteDeCaja("/ReportesJasper/", "ReporteCaja.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Caja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbreporteActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtcaja);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        if(String.valueOf(idcaja).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado caja");
        }else{
            ca.jbmodificar(Double.parseDouble(jtxtcaja.getText()), 
                    jtxtfechaactual.getText(), 
                        Integer.parseInt(jtxtidusuario.getText()), 
                        Menu.idcompania,
                        idcaja);
            ca.muestraRegistros(jtcaja, Menu.idcompania);
            ca.jbcancelar(jtxtcaja);
        }
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        if(String.valueOf(idcaja).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado caja");
        }else{
            ca.jbeliminar(idcaja, Menu.idcompania);
            ca.jbcancelar(jtxtcaja);
            ca.muestraRegistros(jtcaja, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

         ca.jbcancelar(jtxtcaja);
         ca.muestraRegistros(jtcaja, Menu.idcompania);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        if(jtxtcaja.getText().equals("") || jtxtfechaactual.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            ca.jbguardar(Double.parseDouble(jtxtcaja.getText()), 
                    jtxtfechaactual.getText(), 
                    Integer.parseInt(jtxtidusuario.getText()),
                    Menu.idcompania);
            ca.jbcancelar(jtxtcaja);
            ca.muestraRegistros(jtcaja, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        Instancias._caja = null;
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Caja().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbeliminar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jbmodificar;
    public static javax.swing.JButton jbreporte;
    private javax.swing.JButton jbsalir;
    private com.toedter.calendar.JDateChooser jdcfecha;
    public static javax.swing.JMenu jmacciones;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_eliminar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenuItem jmi_modificar;
    public static javax.swing.JMenuItem jmireporte;
    public static javax.swing.JMenu jmreporte;
    private javax.swing.JTable jtcaja;
    private javax.swing.JTextField jtxtcaja;
    private javax.swing.JTextField jtxtfechaactual;
    private javax.swing.JTextField jtxtidusuario;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
    
    public class cronometro implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent evt)
        {
            GregorianCalendar tiempo=new GregorianCalendar();
            int dia, mes, anio, hora, minutos, segundos;
            dia=tiempo.get(Calendar.DAY_OF_MONTH);
            mes=tiempo.get(Calendar.MONTH)+1;
            anio=tiempo.get(Calendar.YEAR);
            hora=tiempo.get(Calendar.HOUR);
            minutos=tiempo.get(Calendar.MINUTE);
            segundos=tiempo.get(Calendar.SECOND);
                  
            fecha=anio+"-"+mes+"-"+dia; 
            jtxtfechaactual.setText(fecha);                              
        }  
    }
    
}
