/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_nuevofolder;
import C.Parametros.datosempresa;
import Frames.Parametros.DatosEmpresa;
import UUID.uuid;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsDevice;
import static java.awt.GraphicsDevice.WindowTranslucency.PERPIXEL_TRANSLUCENT;
import java.awt.GraphicsEnvironment;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Paint;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jraraujo
 */
public class Login extends javax.swing.JFrame {

    Border border, margin;
    String rol = "usu", path;
    URL url;
    ImageIcon fenix;
    JPanel jptransparente;
    JTextAreaMessages jtm = new JTextAreaMessages();
    Instancias inst = new Instancias();
    datosempresa datos = new datosempresa();
    JTableHeader th;
    f_nuevofolder fnf = new f_nuevofolder();
    uuid u = new uuid();    
    DatosEmpresa emp = new DatosEmpresa();  
    int idempresa;
    
    /**
     * Creates new form Login
     */
    public Login() {  

        initComponents();
        fnf.crearFolder();
        this.setLocationRelativeTo(null);
        jtempresas.setDefaultEditor(Object.class, null);
        th = jtempresas.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        datos.mostrarEmpresasLogin(jtempresas);
        jtempresas.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtempresas = new javax.swing.JTable();
        jplogin = new javax.swing.JPanel();
        jlusuario = new javax.swing.JLabel();
        jtusuario = new javax.swing.JTextField();
        jtcont = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbaceptar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Color.decode("#710533")
        );
        setIconImage(getIconImage());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtempresas.setForeground(new java.awt.Color(0, 102, 102));
        jtempresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Empresa", "RFC"
            }
        ));
        jtempresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtempresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtempresas);

        jplogin.setBackground(new java.awt.Color(255, 255, 255));
        jplogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 51), new java.awt.Color(153, 0, 51), null, null));

        jlusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jlusuario.setText("Usuario:");
        jlusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlusuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlusuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlusuarioMouseExited(evt);
            }
        });

        jtusuario.setEnabled(false);
        jtusuario.setMaximumSize(new java.awt.Dimension(7, 20));
        jtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtusuarioActionPerformed(evt);
            }
        });
        jtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtusuarioKeyPressed(evt);
            }
        });

        jtcont.setEnabled(false);
        jtcont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtcontKeyPressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contrasenia.png"))); // NOI18N
        jLabel2.setText("Contraseña:");

        javax.swing.GroupLayout jploginLayout = new javax.swing.GroupLayout(jplogin);
        jplogin.setLayout(jploginLayout);
        jploginLayout.setHorizontalGroup(
            jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jploginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jlusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jtcont))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jploginLayout.setVerticalGroup(
            jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jploginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlusuario)
                    .addComponent(jtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/himawari.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jplogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jplogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jbaceptar.setText("Aceptar");
        jbaceptar.setEnabled(false);
        jbaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaceptarActionPerformed(evt);
            }
        });

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbaceptar)
                    .addComponent(jbcancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtusuarioActionPerformed

    private void jbaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaceptarActionPerformed

//        u.generarUUID();
//        datos.obtenRFC(idempresa);
//        if(datos.obtenRegistro(licencia._LICENCIA)==false){
//            jtm.jTextAreaMessage("Licence not valid");
//            emp.setVisible(true);
//            this.dispose();
//        }else{
//            int cntd = uuid._CONECTADO = 1;
//            datos.actualizaEstadoCC(cntd);
            C.Login.Login log = new C.Login.Login();
            char[] charcont = jtcont.getPassword();
            String strcont = new String(charcont);
            log.verificaUsuario(jtusuario.getText(), strcont, rol);
            if(log.valorusuario==true && log.valorcontrasenia == true){
                try {
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                jtm.jTextAreaMessage("Usuario o contraseña invalidos");
                System.exit(0);
            }
        
        
    }//GEN-LAST:event_jbaceptarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        System.exit(0);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jtusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtusuarioKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            C.Login.Login log = new C.Login.Login();
            char[] charcont = jtcont.getPassword();
            String strcont = new String(charcont);
            log.verificaUsuario(jtusuario.getText(), strcont, rol);
            if(log.valorusuario==true && log.valorcontrasenia == true){
                try {
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                jtm.jTextAreaMessage("Usuario o contraseña invalidos");
                this.dispose();
            }        
        }
        
    }//GEN-LAST:event_jtusuarioKeyPressed

    private void jtcontKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtcontKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            C.Login.Login log = new C.Login.Login();
            char[] charcont = jtcont.getPassword();
            String strcont = new String(charcont);
            log.verificaUsuario(jtusuario.getText(), strcont, rol);
            if(log.valorusuario==true && log.valorcontrasenia == true){
                try {
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                jtm.jTextAreaMessage("Usuario o contraseña invalidos");
                this.dispose();
            }        
        }
        
    }//GEN-LAST:event_jtcontKeyPressed

    private void jlusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlusuarioMouseEntered

        border = new SoftBevelBorder(BevelBorder.RAISED);
        margin = jlusuario.getBorder();
        jlusuario.setBorder(new CompoundBorder(border, margin));
        
    }//GEN-LAST:event_jlusuarioMouseEntered

    private void jlusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlusuarioMouseExited

        jlusuario.setBorder(null);
        
    }//GEN-LAST:event_jlusuarioMouseExited

    private void jlusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlusuarioMouseClicked

        path = "/Imagenes/usuario.png";
        url = this.getClass().getResource(path);
        fenix = new ImageIcon(url); 
        
        jlusuario.setVisible(false);
        jtusuario.setEnabled(true);
        jtcont.setEnabled(true);
        jbaceptar.setEnabled(true);
        rol = "adm";
        Menu.rol_login = rol;
        JLabel jladministrador = new JLabel();
        jladministrador.setName("jladministrador");
        jladministrador.setText("Admin.:");
        jladministrador.setPreferredSize(new Dimension(118, 30));
        jladministrador.setBounds(15, 12, 118, 30);
        jladministrador.setIcon(fenix);
        jladministrador.setVisible(true);
        jladministrador.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                jladministrador.setVisible(false);
                jlusuario.setVisible(true);
                rol = "usu";                
                jtusuario.setEnabled(false);
                jtcont.setEnabled(false);
                jbaceptar.setEnabled(false);
            }

            @Override
            public void mousePressed(MouseEvent e) {
               
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                border = new SoftBevelBorder(BevelBorder.RAISED);
                margin = jladministrador.getBorder();
                jladministrador.setBorder(new CompoundBorder(border, margin));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jladministrador.setBorder(null);
            }
            
        });
        jplogin.add(jladministrador);
        
    }//GEN-LAST:event_jlusuarioMouseClicked

    private void jtempresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtempresasMouseClicked

        DatosEmpresa.idempresa = Integer.parseInt(jtempresas.getValueAt(jtempresas.getSelectedRow(), 0).toString());
        idempresa = Integer.parseInt(jtempresas.getValueAt(jtempresas.getSelectedRow(), 0).toString());
        Menu.idcompania = Integer.parseInt(jtempresas.getValueAt(jtempresas.getSelectedRow(), 0).toString());
        Menu.compania = jtempresas.getValueAt(jtempresas.getSelectedRow(), 1).toString();
        if(!Menu.compania.equals("")){
            jtusuario.setEnabled(true);
            jtcont.setEnabled(true);
            jbaceptar.setEnabled(true);
        }
        
    }//GEN-LAST:event_jtempresasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        GraphicsEnvironment ge = 
            GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        boolean isPerPixelTranslucencySupported = 
            gd.isWindowTranslucencySupported(PERPIXEL_TRANSLUCENT);

        //If translucent windows aren't supported, exit.
        if (!isPerPixelTranslucencySupported) {
            System.out.println(
                "Per-pixel translucency is not supported");
                System.exit(0);
        }
        JFrame.setDefaultLookAndFeelDecorated(true);

        // Create the GUI on the event-dispatching thread
        SwingUtilities.invokeLater(() -> {
            Login log = new Login();            
            // Display the window.
            log.setVisible(true);
        });

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbaceptar;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JLabel jlusuario;
    private javax.swing.JPanel jplogin;
    public static javax.swing.JPasswordField jtcont;
    private javax.swing.JTable jtempresas;
    private javax.swing.JTextField jtusuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}



