/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.EntradasProducto;

import C.EntradasProducto.entradasproducto;
import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import Frames.Listados.ListarAlmacenes;
import Frames.Listados.ListarAnaqueles;
import Frames.Listados.ListarBins;
import Frames.Listados.ListarPasillos;
import Frames.Menu;
import ReportesJasper.reportes;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author jraraujo
 */
public class EntradasProducto extends javax.swing.JFrame {
    String whoisselected;
    Instancias inst = new Instancias();
    entradasproducto entpro= new entradasproducto();
    JTextAreaMessages jtm = new JTextAreaMessages();
    reportes rep = new reportes();
    CheckAccess cha = new CheckAccess();
    JTableHeader th;
    int identradaproducto;

    /**
     * Creates new form EntradasAlmacen
     */
    public EntradasProducto() {
        initComponents();
        this.setLocationRelativeTo(null);        
        //jtentradasproducto.setDefaultEditor(Object.class, null);
        th = jtentradasproducto.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        entpro.mostrarEntradas(jtentradasproducto, Menu.idcompania);
        cha.revisarAccesosEntradaProductos(Menu.idusu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jbmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jbidcompra = new javax.swing.JButton();
        jtxtidcompra = new javax.swing.JTextField();
        jbalmacen = new javax.swing.JButton();
        jtxtidalmacen = new javax.swing.JTextField();
        jbpasillo = new javax.swing.JButton();
        jtxtidpasillo = new javax.swing.JTextField();
        jbanaquel = new javax.swing.JButton();
        jtxtidanaquel = new javax.swing.JTextField();
        jbbin = new javax.swing.JButton();
        jtxtidbin = new javax.swing.JTextField();
        jbproducto = new javax.swing.JButton();
        jtxtidproducto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jtxtcant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbguardarcantidad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtcomentarios = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jdcentrada = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtentradasproducto = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmacciones = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jmi_salir = new javax.swing.JMenuItem();
        jmreporte = new javax.swing.JMenu();
        jmi_reporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Entradas de Almacen]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setEnabled(false);
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator1);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setEnabled(false);
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator2);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setEnabled(false);
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setBorder(null);
        jbmodificar.setEnabled(false);
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator3);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setEnabled(false);
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator5);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setToolTipText("");
        jbreporte.setBorder(null);
        jbreporte.setEnabled(false);
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator6);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-return-purchase-24.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator4);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator7);

        jPanel1.setBackground(Color.decode("#C70039"));

        jPanel6.setBackground(Color.decode("#C70039"));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jbidcompra.setText("Id Compra:");
        jbidcompra.setEnabled(false);
        jbidcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbidcompraActionPerformed(evt);
            }
        });

        jtxtidcompra.setEditable(false);

        jbalmacen.setText("Almacen:");
        jbalmacen.setEnabled(false);
        jbalmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbalmacenActionPerformed(evt);
            }
        });

        jtxtidalmacen.setEditable(false);

        jbpasillo.setText("Pasillo");
        jbpasillo.setEnabled(false);
        jbpasillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpasilloActionPerformed(evt);
            }
        });

        jtxtidpasillo.setEditable(false);

        jbanaquel.setText("Anaquel");
        jbanaquel.setEnabled(false);
        jbanaquel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbanaquelActionPerformed(evt);
            }
        });

        jtxtidanaquel.setEditable(false);

        jbbin.setText("Bin:");
        jbbin.setEnabled(false);
        jbbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbinActionPerformed(evt);
            }
        });

        jtxtidbin.setEditable(false);

        jbproducto.setText("Producto:");
        jbproducto.setEnabled(false);
        jbproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbproductoActionPerformed(evt);
            }
        });

        jtxtidproducto.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbanaquel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbpasillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbalmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbidcompra, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jbbin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtidbin)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxtidcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtxtidalmacen)
                    .addComponent(jtxtidpasillo)
                    .addComponent(jtxtidanaquel)
                    .addComponent(jtxtidproducto))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbidcompra)
                    .addComponent(jtxtidcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbalmacen)
                    .addComponent(jtxtidalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbpasillo)
                    .addComponent(jtxtidpasillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbanaquel)
                    .addComponent(jtxtidanaquel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbbin)
                    .addComponent(jtxtidbin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbproducto)
                    .addComponent(jtxtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);

        jPanel4.setOpaque(false);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cantidad:");

        jbguardarcantidad.setText("Actualizar Cantidad");
        jbguardarcantidad.setEnabled(false);
        jbguardarcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarcantidadActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Comentarios"));

        jtxtcomentarios.setColumns(20);
        jtxtcomentarios.setLineWrap(true);
        jtxtcomentarios.setRows(5);
        jtxtcomentarios.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jtxtcomentarios);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fecha:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jbguardarcantidad)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtcant)
                            .addComponent(jdcentrada, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcentrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbguardarcantidad)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        jTabbedPane1.addTab("Entradas al Almacen", jPanel1);

        jtentradasproducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtentradasproducto.setForeground(new java.awt.Color(0, 102, 102));
        jtentradasproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Entrada", "Id Compra", "Id Almacen", "Id Pasillo", "Id Anaquel", "Id Bin", "Id Producto", "Producto", "Cant act.", "Fecha Entrada", "Comentarios", "Id Empleado", "Id Empresa"
            }
        ));
        jtentradasproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtentradasproductoMouseClicked(evt);
            }
        });
        jtentradasproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtentradasproductoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtentradasproducto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(Color.decode("#C70039"));

        jmacciones.setForeground(new java.awt.Color(255, 255, 255));
        jmacciones.setText("Acciones");
        jmacciones.setEnabled(false);

        jmi_guardar.setText("Guardar");
        jmi_guardar.setEnabled(false);
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.setEnabled(false);
        jmi_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cancelarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_cancelar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.setEnabled(false);
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_eliminar);

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmacciones.add(jMenuItem1);

        jmi_exportar.setText("Exportar");
        jmi_exportar.setEnabled(false);
        jmacciones.add(jmi_exportar);
        jmacciones.add(jSeparator8);

        jmi_salir.setText("Salir");
        jmi_salir.setEnabled(false);
        jmacciones.add(jmi_salir);

        jMenuBar1.add(jmacciones);

        jmreporte.setForeground(new java.awt.Color(255, 255, 255));
        jmreporte.setText("Reporte");
        jmreporte.setEnabled(false);

        jmi_reporte.setText("Reporte");
        jmi_reporte.setEnabled(false);
        jmi_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reporteActionPerformed(evt);
            }
        });
        jmreporte.add(jmi_reporte);

        jMenuBar1.add(jmreporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbidcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbidcompraActionPerformed

        inst.getInstanciasListarCompras();

    }//GEN-LAST:event_jbidcompraActionPerformed

    private void jbalmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbalmacenActionPerformed

        whoisselected = "ent_jbidalmacen";
        ListarAlmacenes.whoisselected = whoisselected;
        inst.getInstanciasListarAlmacenes();

    }//GEN-LAST:event_jbalmacenActionPerformed

    private void jbpasilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpasilloActionPerformed

        whoisselected = "ent_jbidpasillo";
        ListarPasillos.whoisselected = whoisselected;
        inst.getInstanciasListarPasillos();

    }//GEN-LAST:event_jbpasilloActionPerformed

    private void jbanaquelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbanaquelActionPerformed

        whoisselected = "ent_idanaquel";
        ListarAnaqueles.whoisselected = whoisselected;
        inst.getInstanciasListarAnaqueles();

    }//GEN-LAST:event_jbanaquelActionPerformed

    private void jbproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproductoActionPerformed

        inst.getInstanciasListarProductosXCompra();

    }//GEN-LAST:event_jbproductoActionPerformed

    private void jbbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbinActionPerformed

        whoisselected = "ent_idbin";
        ListarBins.whoisselected = whoisselected;
        inst.getInstanciasListarBin();

    }//GEN-LAST:event_jbbinActionPerformed

    private void jbguardarcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarcantidadActionPerformed

        if(jtxtidcompra.equals("") || jtxtidproducto.getText().equals("")
                || jtxtidalmacen.getText().equals("") || jtxtidpasillo.getText().equals("")
                || jtxtidanaquel.getText().equals("") || jtxtidbin.getText().equals("") 
                || jtxtcant.getText().equals("") || String.valueOf(identradaproducto).equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            entpro.obtenCantAct(Integer.parseInt(jtxtidcompra.getText()),
                    Integer.parseInt(jtxtidproducto.getText()),
                    Integer.parseInt(jtxtidalmacen.getText()),
                    Integer.parseInt(jtxtidpasillo.getText()),
                    Integer.parseInt(jtxtidanaquel.getText()),
                    Integer.parseInt(jtxtidbin.getText()),
                    Menu.idcompania);
            entpro.updateCantidad(Integer.parseInt(jtxtidcompra.getText()),
                    Integer.parseInt(jtxtidalmacen.getText()),
                    Integer.parseInt(jtxtidpasillo.getText()),
                    Integer.parseInt(jtxtidanaquel.getText()),
                    Integer.parseInt(jtxtidbin.getText()),
                    Integer.parseInt(jtxtidproducto.getText()),
                    Integer.parseInt(jtxtcant.getText()), 
                    Menu.idusu,
                    Menu.idcompania,
                    identradaproducto);
            entpro.limpiarEntradas(jtxtidcompra, jtxtidalmacen, jtxtidanaquel, 
                jtxtidpasillo, jtxtidbin, jtxtidproducto, jtxtcant, jdcentrada, jtxtcomentarios);
        }

    }//GEN-LAST:event_jbguardarcantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Instancias._entradasproducto = null;
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._entradasproducto = null;
        
    }//GEN-LAST:event_formWindowClosing

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
                
        if(jtxtidcompra.equals("") || jtxtidproducto.getText().equals("")
                || jtxtidalmacen.getText().equals("") || jtxtidpasillo.getText().equals("")
                || jtxtidanaquel.getText().equals("") || jtxtidbin.getText().equals("") 
                || jtxtcant.getText().equals("") || String.valueOf(identradaproducto).equals("")
                || jdcentrada.getDate() == null){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            java.sql.Date _fecha = new java.sql.Date(jdcentrada.getDate().getTime());
            entpro.jbguardar(Integer.parseInt(jtxtidcompra.getText()), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()),
                    Integer.parseInt(jtxtidproducto.getText()),
                    Integer.parseInt(jtxtcant.getText()),
                    _fecha,
                    jtxtcomentarios.getText(),
                    Menu.idusu, 
                    Menu.idcompania);
            entpro.limpiarEntradas(jtxtidcompra, jtxtidalmacen, jtxtidanaquel, 
                jtxtidpasillo, jtxtidbin, jtxtidproducto, jtxtcant, jdcentrada, jtxtcomentarios);
            entpro.mostrarEntradas(jtentradasproducto, Menu.idcompania);
         }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        entpro.limpiarEntradas(jtxtidcompra, jtxtidalmacen, jtxtidanaquel, 
                jtxtidpasillo, jtxtidbin, jtxtidproducto, jtxtcant, jdcentrada, jtxtcomentarios);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jmi_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cancelarActionPerformed

        entpro.limpiarEntradas(jtxtidcompra, jtxtidalmacen, jtxtidanaquel, 
                jtxtidpasillo, jtxtidbin, jtxtidproducto, jtxtcant, jdcentrada, jtxtcomentarios);
        
    }//GEN-LAST:event_jmi_cancelarActionPerformed

    private void jtentradasproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtentradasproductoMouseClicked

        try {
            identradaproducto = Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 0).toString());
            jtxtidcompra.setText(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 1).toString());
            jtxtidalmacen.setText(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 2).toString());
            jtxtidpasillo.setText(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 3).toString());
            jtxtidanaquel.setText(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 4).toString());
            jtxtidbin.setText(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 5).toString());
            jtxtidproducto.setText(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 6).toString());
            jtxtcant.setText(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 8).toString());
            String fechaentrada = jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 9).toString();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date date = df.parse(fechaentrada);
            jdcentrada.setDate(date);
            jtxtcomentarios.setText(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 10).toString());
            int idempleado = Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 9).toString());
            int idempresa = Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 10).toString());
        } catch (ParseException ex) {
            Logger.getLogger(EntradasProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jtentradasproductoMouseClicked

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed

        if(jtxtidcompra.equals("") || jtxtidproducto.getText().equals("")
                || jtxtidalmacen.getText().equals("") || jtxtidpasillo.getText().equals("")
                || jtxtidanaquel.getText().equals("") || jtxtidbin.getText().equals("") 
                || jtxtcant.getText().equals("") || String.valueOf(identradaproducto).equals("")
                || jdcentrada.getDate() == null){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            java.sql.Date _fecha = new java.sql.Date(jdcentrada.getDate().getTime());
            entpro.jbguardar(Integer.parseInt(jtxtidcompra.getText()), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()),
                    Integer.parseInt(jtxtidproducto.getText()),
                    Integer.parseInt(jtxtcant.getText()),
                    _fecha,
                    jtxtcomentarios.getText(),
                    Menu.idusu, 
                    Menu.idcompania);
            entpro.limpiarEntradas(jtxtidcompra, jtxtidalmacen, jtxtidanaquel, 
                jtxtidpasillo, jtxtidbin, jtxtidproducto, jtxtcant, jdcentrada, jtxtcomentarios);
            entpro.mostrarEntradas(jtentradasproducto, Menu.idcompania);
         }
        
    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        if(String.valueOf(identradaproducto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un registro para modificar");
        }else{
            entpro.jbeliminar(identradaproducto, Menu.idcompania);
            entpro.limpiarEntradas(jtxtidcompra, jtxtidalmacen, jtxtidanaquel, 
                jtxtidpasillo, jtxtidbin, jtxtidproducto, jtxtcant, jdcentrada, jtxtcomentarios);
            entpro.mostrarEntradas(jtentradasproducto, Menu.idcompania);
        }
        
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed

        if(String.valueOf(identradaproducto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un registro para modificar");
        }else{
            entpro.jbeliminar(identradaproducto, Menu.idcompania);
            entpro.limpiarEntradas(jtxtidcompra, jtxtidalmacen, jtxtidanaquel, 
                jtxtidpasillo, jtxtidbin, jtxtidproducto, jtxtcant, jdcentrada, jtxtcomentarios);
            entpro.mostrarEntradas(jtentradasproducto, Menu.idcompania);
        }        
        
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed

        try {
            rep.EmisionReporteDeEntradasDeProducto("/ReportesJasper/", "ReporteEntradasDeProducto.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(EntradasProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbreporteActionPerformed

    private void jmi_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reporteActionPerformed

        try {
            rep.EmisionReporteDeEntradasDeProducto("/ReportesJasper/", "ReporteEntradasDeProducto.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(EntradasProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmi_reporteActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtentradasproducto);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jtentradasproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtentradasproductoKeyReleased

        jtentradasproducto.setSurrendersFocusOnKeystroke(true);
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             entpro.obtenCantAct(Integer.parseInt(jtxtidcompra.getText()),
                    Integer.parseInt(jtxtidproducto.getText()),
                    Integer.parseInt(jtxtidalmacen.getText()),
                    Integer.parseInt(jtxtidpasillo.getText()),
                    Integer.parseInt(jtxtidanaquel.getText()),
                    Integer.parseInt(jtxtidbin.getText()),
                    Menu.idcompania);
            entpro.updateCantidad(Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 1).toString()),
                    Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 2).toString()),
                    Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 3).toString()),
                    Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 4).toString()),
                    Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 5).toString()),
                    Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 6).toString()),
                    Integer.parseInt(jtentradasproducto.getValueAt(jtentradasproducto.getSelectedRow(), 7).toString()), 
                    Menu.idusu,
                    Menu.idcompania,
                    identradaproducto);
            entpro.limpiarEntradas(jtxtidcompra, jtxtidalmacen, jtxtidanaquel, 
                jtxtidpasillo, jtxtidbin, jtxtidproducto, jtxtcant, jdcentrada, jtxtcomentarios);
         }
        
    }//GEN-LAST:event_jtentradasproductoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        inst.getInstanciasEntradasDesdeDevoluciones();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        if(jtxtidcompra.equals("") || jtxtidproducto.getText().equals("")
                || jtxtidalmacen.getText().equals("") || jtxtidpasillo.getText().equals("")
                || jtxtidanaquel.getText().equals("") || jtxtidbin.getText().equals("") 
                || jtxtcant.getText().equals("") || String.valueOf(identradaproducto).equals("")
                || jdcentrada.getDate() == null){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            java.sql.Date _fecha = new java.sql.Date(jdcentrada.getDate().getTime());
            entpro.jbmodificar(Integer.parseInt(jtxtidcompra.getText()), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()),
                    Integer.parseInt(jtxtidproducto.getText()),
                    Integer.parseInt(jtxtcant.getText()),
                    _fecha,
                    jtxtcomentarios.getText(),
                    Menu.idusu, 
                    Menu.idcompania,
                    identradaproducto);
        }
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        if(jtxtidcompra.equals("") || jtxtidproducto.getText().equals("")
                || jtxtidalmacen.getText().equals("") || jtxtidpasillo.getText().equals("")
                || jtxtidanaquel.getText().equals("") || jtxtidbin.getText().equals("") 
                || jtxtcant.getText().equals("") || String.valueOf(identradaproducto).equals("")
                || jdcentrada.getDate() == null){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            java.sql.Date _fecha = new java.sql.Date(jdcentrada.getDate().getTime());
            entpro.jbmodificar(Integer.parseInt(jtxtidcompra.getText()), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()),
                    Integer.parseInt(jtxtidproducto.getText()),
                    Integer.parseInt(jtxtcant.getText()),
                    _fecha,
                    jtxtcomentarios.getText(),
                    Menu.idusu, 
                    Menu.idcompania,
                    identradaproducto);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradasProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EntradasProducto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbalmacen;
    public static javax.swing.JButton jbanaquel;
    public static javax.swing.JButton jbbin;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbeliminar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jbguardarcantidad;
    public static javax.swing.JButton jbidcompra;
    public static javax.swing.JButton jbmodificar;
    public static javax.swing.JButton jbpasillo;
    public static javax.swing.JButton jbproducto;
    public static javax.swing.JButton jbreporte;
    private com.toedter.calendar.JDateChooser jdcentrada;
    public static javax.swing.JMenu jmacciones;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_eliminar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenuItem jmi_reporte;
    public static javax.swing.JMenuItem jmi_salir;
    public static javax.swing.JMenu jmreporte;
    public static javax.swing.JTable jtentradasproducto;
    public static javax.swing.JTextField jtxtcant;
    private javax.swing.JTextArea jtxtcomentarios;
    public static javax.swing.JTextField jtxtidalmacen;
    public static javax.swing.JTextField jtxtidanaquel;
    public static javax.swing.JTextField jtxtidbin;
    public static javax.swing.JTextField jtxtidcompra;
    public static javax.swing.JTextField jtxtidpasillo;
    public static javax.swing.JTextField jtxtidproducto;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }   
}
