/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Devoluciones;

import C.Devoluciones.devoluciones;
import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import Frames.Listados.ListarAlmacenes;
import Frames.Listados.ListarAnaqueles;
import Frames.Listados.ListarBins;
import Frames.Listados.ListarPasillos;
import Frames.Listados.ListarProductos;
import Frames.Menu;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jraraujo
 */
public class Devoluciones extends javax.swing.JFrame {

    devoluciones dev = new devoluciones();
    JTextAreaMessages jtm = new JTextAreaMessages();
    CheckAccess cha = new CheckAccess();
    int iddevolucion;
    public static String whoisselected;
    Instancias inst = new Instancias();
    JTableHeader th;
        /**
     * Creates new form Devoluciones
     */
    public Devoluciones() {
        initComponents();
        this.setLocationRelativeTo(null); 
        jtdevoluciones.setDefaultEditor(Object.class, null);
        th = jtdevoluciones.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        cha.revisarAccesosDevoluciones(Menu.idusu);
        dev.mostrarDevoluciones(jtdevoluciones, Menu.idcompania);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jScrollBar1 = new javax.swing.JScrollBar();
        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jbmodificar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        salir = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbidventa = new javax.swing.JButton();
        jtxtidventa = new javax.swing.JTextField();
        jbidproducto = new javax.swing.JButton();
        jtxtidproducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jdcfecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtrazon = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jbidalmacen = new javax.swing.JButton();
        jtxtidalmacen = new javax.swing.JTextField();
        jbidpasillo = new javax.swing.JButton();
        jtxtidpasillo = new javax.swing.JTextField();
        jbidanaquel = new javax.swing.JButton();
        jtxtidanaquel = new javax.swing.JTextField();
        jbidbin = new javax.swing.JButton();
        jtxtidbin = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtdevoluciones = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmacciones = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmreporte = new javax.swing.JMenu();
        jmi_reporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Devoluciónes]");
        setBackground(Color.decode("#C70039"));
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setEnabled(false);
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator2);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setEnabled(false);
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator3);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setEnabled(false);
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator4);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setBorder(null);
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.setEnabled(false);
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator5);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setEnabled(false);
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator8);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setBorder(null);
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setEnabled(false);
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator9);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jToolBar1.add(salir);
        jToolBar1.add(jSeparator10);

        jPanel3.setBackground(Color.decode("#C70039"));
        jPanel3.setPreferredSize(new Dimension(686, 200));

        jPanel1.setOpaque(false);

        jbidventa.setText("Id Venta:");
        jbidventa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbidventa.setEnabled(false);
        jbidventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbidventaActionPerformed(evt);
            }
        });

        jtxtidventa.setEditable(false);

        jbidproducto.setText("Producto:");
        jbidproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbidproducto.setEnabled(false);
        jbidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbidproductoActionPerformed(evt);
            }
        });

        jtxtidproducto.setEditable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fecha devolucion:");

        jdcfecha.setDateFormatString("yyyy-MM-dd");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Razón de devolución y detalles"));

        jtxtrazon.setColumns(20);
        jtxtrazon.setRows(5);
        jtxtrazon.setBorder(null);
        jScrollPane1.setViewportView(jtxtrazon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jbidproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbidventa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtidventa)
                            .addComponent(jtxtidproducto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jdcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 70, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbidventa)
                    .addComponent(jtxtidventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbidproducto)
                    .addComponent(jtxtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jdcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new Dimension(300, 186));

        jbidalmacen.setText("Almacen:");
        jbidalmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbidalmacen.setEnabled(false);
        jbidalmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbidalmacenActionPerformed(evt);
            }
        });

        jtxtidalmacen.setEditable(false);
        jtxtidalmacen.setPreferredSize(new Dimension(198, 22));

        jbidpasillo.setText("Pasillo:");
        jbidpasillo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbidpasillo.setEnabled(false);
        jbidpasillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbidpasilloActionPerformed(evt);
            }
        });

        jtxtidpasillo.setEditable(false);
        jtxtidpasillo.setPreferredSize(new Dimension(198, 22));

        jbidanaquel.setText("Anaquel:");
        jbidanaquel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbidanaquel.setEnabled(false);
        jbidanaquel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbidanaquelActionPerformed(evt);
            }
        });

        jtxtidanaquel.setEditable(false);
        jtxtidanaquel.setPreferredSize(new Dimension(198, 22));

        jbidbin.setText("Bin:");
        jbidbin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbidbin.setEnabled(false);
        jbidbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbidbinActionPerformed(evt);
            }
        });

        jtxtidbin.setEditable(false);
        jtxtidbin.setPreferredSize(new Dimension(198, 22));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbidbin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbidanaquel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbidpasillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbidalmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtidpasillo)
                    .addComponent(jtxtidanaquel)
                    .addComponent(jtxtidbin, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jtxtidalmacen))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbidalmacen)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtxtidalmacen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbidpasillo)
                    .addComponent(jtxtidpasillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbidanaquel)
                    .addComponent(jtxtidanaquel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbidbin)
                    .addComponent(jtxtidbin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);

        jTabbedPane1.addTab("Registro de Devoluciónes", jPanel3);

        jPanel4.setBackground(Color.decode("#C70039"));
        jPanel4.setOpaque(false);

        jtdevoluciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtdevoluciones.setForeground(new java.awt.Color(0, 102, 102));
        jtdevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Id Venta", "Id Producto", "Fecha", "Razón", "Id Almacen", "Id Pasillo", "Id Anaquel", "Id Bin", "Id Empleado", "Id Empresa"
            }
        ));
        jScrollPane2.setViewportView(jtdevoluciones);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(Color.decode("#C70039"));

        jmacciones.setForeground(new java.awt.Color(255, 255, 255));
        jmacciones.setText("Acciones");
        jmacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmacciones.setEnabled(false);

        jmi_guardar.setText("Guardar");
        jmi_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_guardar.setEnabled(false);
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_cancelar.setEnabled(false);
        jmi_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cancelarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_cancelar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_eliminar.setEnabled(false);
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_eliminar);

        jmi_modificar.setText("Modificar");
        jmi_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_modificar.setEnabled(false);
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_modificar);

        jmi_exportar.setText("Exportar");
        jmi_exportar.setEnabled(false);
        jmi_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_exportarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_exportar);
        jmacciones.add(jSeparator1);

        jMenuItem5.setText("Salir");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmacciones.add(jMenuItem5);

        jMenuBar1.add(jmacciones);

        jmreporte.setForeground(new java.awt.Color(255, 255, 255));
        jmreporte.setText("Reporte");
        jmreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmreporte.setEnabled(false);

        jmi_reporte.setText("Reporte");
        jmi_reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_reporte.setEnabled(false);
        jmi_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reporteActionPerformed(evt);
            }
        });
        jmreporte.add(jmi_reporte);

        jMenuBar1.add(jmreporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked

        Instancias._devoluciones = null;
        this.dispose();
        
    }//GEN-LAST:event_salirMouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        Instancias._devoluciones = null;
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._devoluciones = null;
        
    }//GEN-LAST:event_formWindowClosing

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed

       if(jtxtidventa.getText().equals("") || jtxtidproducto.getText().equals("") 
                || jdcfecha.getDate() == null
                || jtxtrazon.getText().equals("") 
                || jtxtidalmacen.getText().equals("") 
                || jtxtidpasillo.getText().equals("")
                || jtxtidanaquel.getText().equals("")
                || jtxtidbin.getText().equals("")){
            jtm.jTextAreaMessage("Existen valores vacios");
        }else{
            dev.jbguardar(Integer.parseInt(jtxtidventa.getText()), 
                    Integer.parseInt(jtxtidproducto.getText()), 
                    jdcfecha, 
                    jtxtrazon.getText(), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()), 
                    Menu.idusu, 
                    Menu.idcompania);
            dev.mostrarDevoluciones(jtdevoluciones, Menu.idcompania);
            dev.jbcancelar(jtxtidventa, jtxtidproducto, jdcfecha, jtxtrazon, 
                    jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
        }
    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jbidalmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbidalmacenActionPerformed

        whoisselected = "dev_jtxtidalmacen";
        ListarAlmacenes.whoisselected = whoisselected;
        inst.getInstanciasListarAlmacenes();
        
    }//GEN-LAST:event_jbidalmacenActionPerformed

    private void jbidpasilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbidpasilloActionPerformed

        if(jtxtidalmacen.getText().equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un almacen");
        }else{
            whoisselected = "dev_jtxtidpasillo";
            ListarPasillos.whoisselected = whoisselected;     
            inst.getInstanciasListarPasillos();
        }
        
    }//GEN-LAST:event_jbidpasilloActionPerformed

    private void jbidanaquelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbidanaquelActionPerformed

        if(jtxtidpasillo.getText().equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un pasillo");
        }else{
            whoisselected = "dev_jtxtidanaquel";
            ListarAnaqueles.whoisselected = whoisselected;
            inst.getInstanciasListarAnaqueles();
        }
        
    }//GEN-LAST:event_jbidanaquelActionPerformed

    private void jbidbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbidbinActionPerformed

        whoisselected = "dev_jtxtidbin";
        ListarBins.whoisselected = whoisselected;
        inst.getInstanciasListarBin();
        
    }//GEN-LAST:event_jbidbinActionPerformed

    private void jmi_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_exportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtdevoluciones);
        
    }//GEN-LAST:event_jmi_exportarActionPerformed

    private void jbidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbidproductoActionPerformed

        if(jtxtidventa.getText().equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un Id de venta");
        }else{
            whoisselected = "devolucionesproducto";
            ListarProductos.whoisselected = whoisselected;
            inst.getInstanciasListarProductos();
        }
        
    }//GEN-LAST:event_jbidproductoActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        if(jtxtidventa.getText().equals("") || jtxtidproducto.getText().equals("") 
                || jdcfecha.getDate() == null
                || jtxtrazon.getText().equals("") 
                || jtxtidalmacen.getText().equals("") 
                || jtxtidpasillo.getText().equals("")
                || jtxtidanaquel.getText().equals("")
                || jtxtidbin.getText().equals("")){
            jtm.jTextAreaMessage("Existen valores vacios");
        }else{
            dev.jbguardar(Integer.parseInt(jtxtidventa.getText()), 
                    Integer.parseInt(jtxtidproducto.getText()), 
                    jdcfecha, 
                    jtxtrazon.getText(), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()), 
                    Menu.idusu, 
                    Menu.idcompania);
            dev.mostrarDevoluciones(jtdevoluciones, Menu.idcompania);
            dev.jbcancelar(jtxtidventa, jtxtidproducto, jdcfecha, jtxtrazon, 
                    jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        dev.jbcancelar(jtxtidventa, jtxtidproducto, jdcfecha, jtxtrazon, 
                jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
        dev.mostrarDevoluciones(jtdevoluciones, Menu.idcompania);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jmi_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cancelarActionPerformed

        dev.jbcancelar(jtxtidventa, jtxtidproducto, jdcfecha, jtxtrazon, 
                jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
        dev.mostrarDevoluciones(jtdevoluciones, Menu.idcompania);
        
    }//GEN-LAST:event_jmi_cancelarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
        if(String.valueOf(iddevolucion).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            dev.jbeliminar(iddevolucion, Menu.idcompania);
            dev.jbcancelar(jtxtidventa, jtxtidproducto, jdcfecha, jtxtrazon, 
                    jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
            dev.mostrarVentas(jtdevoluciones, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        if(String.valueOf(iddevolucion).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            dev.jbeliminar(iddevolucion, Menu.idcompania);
            dev.jbcancelar(jtxtidventa, jtxtidproducto, jdcfecha, jtxtrazon, 
                    jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
            dev.mostrarVentas(jtdevoluciones, Menu.idcompania);
        }
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        if(String.valueOf(iddevolucion).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un registro");
        }else{
            dev.jbmodificar(Integer.parseInt(jtxtidventa.getText()), 
                    Integer.parseInt(jtxtidproducto.getText()), 
                    jdcfecha, 
                    jtxtrazon.getText(), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()), 
                    Menu.idusu, 
                    Menu.idcompania, 
                    iddevolucion);
            dev.jbcancelar(jtxtidventa, jtxtidproducto, jdcfecha, jtxtrazon, 
                    jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
            dev.mostrarDevoluciones(jtdevoluciones, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed

        if(String.valueOf(iddevolucion).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un registro");
        }else{
            dev.jbmodificar(Integer.parseInt(jtxtidventa.getText()), 
                    Integer.parseInt(jtxtidproducto.getText()), 
                    jdcfecha, 
                    jtxtrazon.getText(), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Integer.parseInt(jtxtidpasillo.getText()), 
                    Integer.parseInt(jtxtidanaquel.getText()), 
                    Integer.parseInt(jtxtidbin.getText()), 
                    Menu.idusu, 
                    Menu.idcompania, 
                    iddevolucion);
            dev.jbcancelar(jtxtidventa, jtxtidproducto, jdcfecha, jtxtrazon, 
                    jtxtidalmacen, jtxtidpasillo, jtxtidanaquel, jtxtidbin);
            dev.mostrarDevoluciones(jtdevoluciones, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtdevoluciones);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jbidventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbidventaActionPerformed

        inst.getInstanciasListarVentas();
        
    }//GEN-LAST:event_jbidventaActionPerformed

    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed

        
        
    }//GEN-LAST:event_jbreporteActionPerformed

    private void jmi_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reporteActionPerformed

        
        
    }//GEN-LAST:event_jmi_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Devoluciones().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbeliminar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jbidalmacen;
    public static javax.swing.JButton jbidanaquel;
    public static javax.swing.JButton jbidbin;
    public static javax.swing.JButton jbidpasillo;
    public static javax.swing.JButton jbidproducto;
    public static javax.swing.JButton jbidventa;
    public static javax.swing.JButton jbmodificar;
    public static javax.swing.JButton jbreporte;
    private com.toedter.calendar.JDateChooser jdcfecha;
    public static javax.swing.JMenu jmacciones;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_eliminar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenuItem jmi_modificar;
    public static javax.swing.JMenuItem jmi_reporte;
    public static javax.swing.JMenu jmreporte;
    private javax.swing.JTable jtdevoluciones;
    public static javax.swing.JTextField jtxtidalmacen;
    public static javax.swing.JTextField jtxtidanaquel;
    public static javax.swing.JTextField jtxtidbin;
    public static javax.swing.JTextField jtxtidpasillo;
    public static javax.swing.JTextField jtxtidproducto;
    public static javax.swing.JTextField jtxtidventa;
    private javax.swing.JTextArea jtxtrazon;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables

    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}
