/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Pasillo;

import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import C.Pasillo.pasillo;
import Frames.Listados.ListarAlmacenes;
import Frames.Menu;
import ReportesJasper.reportes;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author jraraujo
 */
public class Pasillo extends javax.swing.JFrame {

    JTextAreaMessages jtm = new JTextAreaMessages();
    pasillo pas = new pasillo();
    int idpasillo;
    CheckAccess chk = new CheckAccess();
    reportes rep = new reportes();
    JTableHeader th;
    Instancias inst = new Instancias();
    String whoisselected;
    
    /**
     * Creates new form Pasillo
     */
    public Pasillo() {
        initComponents();
        this.setLocationRelativeTo(null);
        //jtpasillo.setDefaultEditor(Object.class, null);
        th = jtpasillo.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        chk.revisarAccesosPasillo(Menu.idusu);
        pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtpasillo = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtxtpasillo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtdescripcion = new javax.swing.JTextArea();
        jbalmacen = new javax.swing.JButton();
        jtxtidalmacen = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_reporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Pasillos]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setEnabled(false);
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator6);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setEnabled(false);
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator5);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setEnabled(false);
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator1);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setBorder(null);
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.setEnabled(false);
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator3);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setEnabled(false);
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator4);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setBorder(null);
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setEnabled(false);
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator2);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel8);
        jToolBar1.add(jSeparator8);

        jtpasillo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtpasillo.setForeground(new java.awt.Color(0, 102, 102));
        jtpasillo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Pasillo", "Descripción", "Id Almacen", "Id Empleadp", "Id Empresa"
            }
        ));
        jtpasillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpasilloMouseClicked(evt);
            }
        });
        jtpasillo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpasilloKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtpasillo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(Color.decode("#C70039"));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pasillo:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        jtxtdescripcion.setColumns(20);
        jtxtdescripcion.setRows(5);
        jScrollPane1.setViewportView(jtxtdescripcion);

        jbalmacen.setText("Almacen:");
        jbalmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbalmacen.setEnabled(false);
        jbalmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbalmacenActionPerformed(evt);
            }
        });

        jtxtidalmacen.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtpasillo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtidalmacen)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtpasillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbalmacen)
                    .addComponent(jtxtidalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel1);

        jTabbedPane1.addTab("Registro de Pasillos", jPanel2);

        jMenuBar1.setBackground(Color.decode("#A80030")
        );

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Acciones");
        jMenu1.setEnabled(false);

        jmi_guardar.setText("Guardar");
        jmi_guardar.setEnabled(false);
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.setEnabled(false);
        jmi_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cancelarActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_cancelar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.setEnabled(false);
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_eliminar);

        jmi_modificar.setText("Modificar");
        jmi_modificar.setEnabled(false);
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_modificar);

        jmi_exportar.setText("Exportar");
        jmi_exportar.setEnabled(false);
        jmi_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_exportarActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_exportar);
        jMenu1.add(jSeparator9);

        jMenuItem7.setText("Salir");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Reporte");
        jMenu2.setEnabled(false);

        jmi_reporte.setText("Reporte");
        jmi_reporte.setEnabled(false);
        jMenu2.add(jmi_reporte);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        Instancias._pasillos = null;
        this.dispose();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._pasillos = null;
        
    }//GEN-LAST:event_formWindowClosing

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        if(String.valueOf(idpasillo).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un pasillo");
        }else{
            pas.jbeliminar(idpasillo);
            pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
            pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

         pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
         pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        if(jtxtpasillo.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            pas.jbguardar(jtxtpasillo.getText(), 
                    jtxtdescripcion.getText(),
                    Integer.parseInt(jtxtidalmacen.getText()),
                    Menu.idusu,
                    Menu.idcompania);
            pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
            pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        if(String.valueOf(idpasillo).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            pas.jbmodificar(jtxtpasillo.getText(), 
                    jtxtdescripcion.getText(), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Menu.idusu, 
                    Menu.idcompania, 
                    idpasillo);
            pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
            pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed

        if(String.valueOf(idpasillo).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            pas.jbmodificar(jtxtpasillo.getText(), 
                    jtxtdescripcion.getText(), 
                    Integer.parseInt(jtxtidalmacen.getText()), 
                    Menu.idusu, 
                    Menu.idcompania, 
                    idpasillo);
            pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
            pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        }        
        
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jmi_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cancelarActionPerformed

          pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
         pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        
    }//GEN-LAST:event_jmi_cancelarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed

        if(String.valueOf(idpasillo).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un pasillo");
        }else{
            pas.jbeliminar(idpasillo);
            pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
            pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtpasillo);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jmi_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_exportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtpasillo);
        
    }//GEN-LAST:event_jmi_exportarActionPerformed

    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed

        try {
            rep.EmisionReporteDeAlmacenes("/ReportesJasper/", "ReportePasillos.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Pasillo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbreporteActionPerformed

    private void jbalmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbalmacenActionPerformed

        whoisselected = "pas_jbidalmacen";
        ListarAlmacenes.whoisselected = whoisselected;
        inst.getInstanciasListarAlmacenes();
        
    }//GEN-LAST:event_jbalmacenActionPerformed

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed

         if(jtxtpasillo.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            pas.jbguardar(jtxtpasillo.getText(), 
                    jtxtdescripcion.getText(),
                    Integer.parseInt(jtxtidalmacen.getText()),
                    Menu.idusu,
                    Menu.idcompania);
            pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
            pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jtpasilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpasilloMouseClicked

        idpasillo = Integer.parseInt(jtpasillo.getValueAt(jtpasillo.getSelectedRow(), 0).toString());
        System.out.println(idpasillo);
        jtxtpasillo.setText(jtpasillo.getValueAt(jtpasillo.getSelectedRow(), 1).toString());
        jtxtdescripcion.setText(jtpasillo.getValueAt(jtpasillo.getSelectedRow(), 2).toString());
        jtxtidalmacen.setText(jtpasillo.getValueAt(jtpasillo.getSelectedRow(), 3).toString());
        
    }//GEN-LAST:event_jtpasilloMouseClicked

    private void jtpasilloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpasilloKeyReleased

        jtpasillo.setSurrendersFocusOnKeystroke(true);
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            pas.jbmodificar(jtpasillo.getValueAt(jtpasillo.getSelectedRow(), 1).toString(), 
                    jtpasillo.getValueAt(jtpasillo.getSelectedRow(), 2).toString(), 
                    Integer.parseInt(jtpasillo.getValueAt(jtpasillo.getSelectedRow(), 3).toString()), 
                    Menu.idusu, 
                    Menu.idcompania, 
                    Integer.parseInt(jtpasillo.getValueAt(jtpasillo.getSelectedRow(), 0).toString()));
            pas.jbcancelar(jtxtpasillo, jtxtdescripcion);
            pas.mostrarRegistros(jtpasillo, 0, 0, Menu.idcompania);
        }
        
    }//GEN-LAST:event_jtpasilloKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pasillo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JMenu jMenu1;
    public static javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbalmacen;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbeliminar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jbmodificar;
    public static javax.swing.JButton jbreporte;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_eliminar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenuItem jmi_modificar;
    public static javax.swing.JMenuItem jmi_reporte;
    private javax.swing.JTable jtpasillo;
    private javax.swing.JTextArea jtxtdescripcion;
    public static javax.swing.JTextField jtxtidalmacen;
    private javax.swing.JTextField jtxtpasillo;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}
