/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Compras;

import C.Anaqueles.anaqueles;
import C.Bin.bin;
import C.Compras.compras;
import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import C.Pasillo.pasillo;
import Frames.Menu;
import Frames.Listados.ListaProveedores;
import Frames.Listados.ListaProductos;
import ReportesJasper.reportes;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author jraraujo
 */
public class Compras extends javax.swing.JFrame {
    
    Image img;
    public static int idproveedor, idproducto;
    int _idproducto;
    compras comp = new compras();
    JTextAreaMessages jtm = new JTextAreaMessages();
    CheckAccess cha = new CheckAccess();
    reportes rep = new reportes();
    pasillo pas = new pasillo();
    anaqueles ana = new anaqueles();
    bin bin = new bin();
    String cmostrador;
    Instancias inst = new Instancias();
    JTableHeader th, th1;
    public static String whoisselected;

    /**
     * Creates new form Compras
     */
    public Compras() {
        initComponents();
        this.setLocationRelativeTo(null);
        th = jtproductos.getTableHeader();
        th1 = jtagregar.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th1.setBackground(Color.decode("#66535A"));
        th1.setForeground(Color.WHITE);
        th.setForeground(Color.WHITE);
        jtproductos.setDefaultEditor(Object.class, null);
        jtagregar.setDefaultEditor(Object.class, null);
        cha.revisarAccesosCompras(Menu.idusu);
        comp.muestraCompras(jtproductos, "", jdcfecha, jdcfecha, Menu.idcompania);  
        comp.total(jtproductos, jtxttotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtproductos = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        jtxtbuscar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jbsalir = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jltotal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtagregar = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtxtbuscarcompras = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtxttotal = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbcproveedor = new javax.swing.JButton();
        jtxtproveedor = new javax.swing.JTextField();
        jtxtticket = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jchkcmostrador = new javax.swing.JCheckBox();
        jbproducto = new javax.swing.JButton();
        jtxtproducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtprecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtcantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtunidad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtobservaciones = new javax.swing.JTextArea();
        jbagregar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jdcfecha = new com.toedter.calendar.JDateChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmacciones = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmreportes = new javax.swing.JMenu();
        jmi_reporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Compras]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtproductos.setAutoCreateRowSorter(true);
        jtproductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jtproductos.setForeground(new java.awt.Color(0, 153, 153));
        jtproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Compra", "Id Proveedor", "Proveedor", "Ticket", "Observaciones", "Fecha", "Total", "Id Empleado", "Id Empresa"
            }
        ));
        jtproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtproductos);

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setEnabled(false);
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator1);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setEnabled(false);
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator2);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setEnabled(false);
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator8);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setEnabled(false);
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator3);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setBorder(null);
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setEnabled(false);
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator4);

        jLabel4.setText("Buscar:");
        jToolBar1.add(jLabel4);

        jtxtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbuscarKeyReleased(evt);
            }
        });
        jToolBar1.add(jtxtbuscar);
        jToolBar1.add(jSeparator6);

        jbsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jbsalir.setBorder(null);
        jbsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbsalir.setFocusable(false);
        jbsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsalirMouseClicked(evt);
            }
        });
        jToolBar1.add(jbsalir);
        jToolBar1.add(jSeparator7);

        jPanel3.setBackground(Color.decode("#C70039"));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total:");
        jLabel5.setToolTipText("");

        jltotal.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jltotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtagregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jtagregar.setForeground(new java.awt.Color(0, 153, 153));
        jtagregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Producto", "Producto", "Cantidad", "unidad", "Precio", "Proveedor"
            }
        ));
        jtagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtagregarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtagregar);

        jPanel5.setBackground(Color.decode("#C70039"));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar:");

        jtxtbuscarcompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbuscarcomprasKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtbuscarcompras)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtbuscarcompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(Color.decode("#C70039"));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total   $:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(Color.decode("#C70039"));

        jPanel1.setBackground(Color.decode("#C70039")
        );
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jbcproveedor.setText("Proveedor:");
        jbcproveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcproveedor.setEnabled(false);
        jbcproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcproveedorActionPerformed(evt);
            }
        });

        jtxtproveedor.setEditable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ticket:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jchkcmostrador.setText("Compra en mostrador");
        jchkcmostrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkcmostradorActionPerformed(evt);
            }
        });

        jbproducto.setText("Producto:");
        jbproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbproducto.setEnabled(false);
        jbproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbproductoActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Precio:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cantidad:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Unidad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jchkcmostrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbcproveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtproveedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtticket, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtproducto)
                    .addComponent(jtxtprecio)
                    .addComponent(jtxtcantidad)
                    .addComponent(jtxtunidad))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbcproveedor)
                    .addComponent(jtxtproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jchkcmostrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbproducto)
                    .addComponent(jtxtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel7.add(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Observaciónes"));

        jtxtobservaciones.setColumns(20);
        jtxtobservaciones.setLineWrap(true);
        jtxtobservaciones.setRows(5);
        jtxtobservaciones.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jtxtobservaciones);

        jbagregar.setText("Agregar");
        jbagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbagregar.setEnabled(false);
        jbagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbagregar)
                .addContainerGap())
        );

        jPanel7.add(jPanel4);

        jPanel10.setOpaque(false);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha de compra");

        jdcfecha.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdcfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel10);

        jTabbedPane1.addTab("Información de Compras", jPanel7);

        jMenuBar2.setBackground(Color.decode("#A80030")
        );

        jmacciones.setForeground(new java.awt.Color(255, 255, 255));
        jmacciones.setText("Acciones");
        jmacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmacciones.setEnabled(false);

        jmi_guardar.setText("Guardar");
        jmi_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_guardar.setEnabled(false);
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_cancelar.setEnabled(false);
        jmi_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cancelarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_cancelar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_eliminar.setEnabled(false);
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_eliminar);

        jmi_exportar.setText("Exportar");
        jmi_exportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_exportar.setEnabled(false);
        jmi_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_exportarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_exportar);
        jmacciones.add(jSeparator5);

        jMenuItem3.setText("Salir");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmacciones.add(jMenuItem3);

        jMenuBar2.add(jmacciones);

        jmreportes.setForeground(new java.awt.Color(255, 255, 255));
        jmreportes.setText("Reportes");
        jmreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmreportes.setEnabled(false);

        jmi_reporte.setText("Reporte");
        jmi_reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_reporte.setEnabled(false);
        jmi_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reporteActionPerformed(evt);
            }
        });
        jmreportes.add(jmi_reporte);

        jMenuBar2.add(jmreportes);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed

        int idcompra_;
        if(jdcfecha.getDate() == null){
            jtm.jTextAreaMessage("Existen campos nulos");
        }else{
            System.out.println("Id Proveedor: "+idproveedor);
            if(jchkcmostrador.isSelected() == true){
                
                comp.jbguardar(idproveedor, 
                        jtxtproveedor.getText(), 
                        cmostrador, 
                        jtxtobservaciones.getText(), 
                        jdcfecha, 
                        Double.parseDouble(jltotal.getText()),
                        Menu.idusu,
                        Menu.idcompania);                
                idcompra_ = comp.obtenerCompra(Menu.idcompania);                    
                System.out.println("Id Compra: "+idcompra_);            
                
                for(int row = 0; row < jtagregar.getRowCount(); row++){
                    comp.jbguardarProductos(idcompra_, 
                            Integer.parseInt(jtagregar.getValueAt(row, 0).toString()), 
                            jtagregar.getValueAt(row, 1).toString(), 
                            Integer.parseInt(jtagregar.getValueAt(row, 2).toString()), 
                            jtagregar.getValueAt(row, 3).toString(),
                            Double.parseDouble(jtagregar.getValueAt(row, 4).toString()),
                            Menu.idusu,
                            Menu.idcompania);
                    }
                
                    comp.jbcancelar(jtxtproveedor, jtxtticket, jtxtproducto, jtxtprecio, 
                            jtxtcantidad, jtxtunidad, jtxtobservaciones, jdcfecha, jltotal);
                    
                    DefaultTableModel dtm = (DefaultTableModel) jtagregar.getModel();
                    int a = jtagregar.getRowCount()-1;
                    for(int i = a; i >= 0; i--){
                        dtm.removeRow(dtm.getRowCount()-1);
                    }
            }else{                
                comp.jbguardar(idproveedor, 
                        jtxtproveedor.getText(), 
                        jtxtticket.getText(), 
                        jtxtobservaciones.getText(), 
                        jdcfecha, 
                        Double.parseDouble(jltotal.getText()),                        
                        Menu.idusu,
                        Menu.idcompania);                        
                
                idcompra_ = comp.obtenerCompra(Menu.idcompania);                    
                System.out.println("Id Compra: "+idcompra_);                                         
                    
                for(int row = 0; row < jtagregar.getRowCount(); row++){
                    comp.jbguardarProductos(idcompra_, 
                            Integer.parseInt(jtagregar.getValueAt(row, 0).toString()), 
                            jtagregar.getValueAt(row, 1).toString(), 
                            Integer.parseInt(jtagregar.getValueAt(row, 2).toString()), 
                            jtagregar.getValueAt(row, 3).toString(),
                            Double.parseDouble(jtagregar.getValueAt(row, 4).toString()),
                            Menu.idusu,
                            Menu.idcompania);
                    }
                
                comp.jbcancelar(jtxtproveedor, jtxtticket, jtxtproducto, jtxtprecio, 
                    jtxtcantidad, jtxtunidad, jtxtobservaciones, jdcfecha, jltotal);
                
                DefaultTableModel dtm = (DefaultTableModel) jtagregar.getModel();
                int a = jtagregar.getRowCount()-1;
                for(int i = a; i >= 0; i--){
                    dtm.removeRow(dtm.getRowCount()-1);
               }                    
            }
            comp.muestraCompras(jtproductos, "", jdcfecha, jdcfecha, Menu.idcompania);  
        }
        
    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jmi_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cancelarActionPerformed

        comp.jbcancelar(jtxtproveedor, jtxtticket, jtxtproducto, jtxtprecio, 
                jtxtcantidad, jtxtunidad, jtxtobservaciones, jdcfecha, jltotal);
        DefaultTableModel dtm = (DefaultTableModel) jtproductos.getModel();
        int a = jtproductos.getRowCount()-1;
        for(int i = a; i >= 0; i--){
            dtm.removeRow(dtm.getRowCount()-1);
        }
        
    }//GEN-LAST:event_jmi_cancelarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed

        int row = jtagregar.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel)jtagregar.getModel();
        modelo.removeRow(row);
        jltotal.setText("");

        double t = 0;
        double p = 0;

       if(jtagregar.getRowCount() > 0){
            for(int i = 0; i < jtagregar.getRowCount(); i++){
                p = Double.parseDouble(jtagregar.getValueAt(i, 4).toString());
                t += p;
            }
            jltotal.setText(String.valueOf(t));
        }       

    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_exportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtproductos);

    }//GEN-LAST:event_jmi_exportarActionPerformed

    private void jbcproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcproveedorActionPerformed

        try {
            jbcproveedor.addMouseListener(new MouseListener(){
                @Override
                public void mouseClicked(MouseEvent e) {
                    ListaProveedores.whosSelected = jbcproveedor;
                }
                
                @Override
                public void mousePressed(MouseEvent e) {
                    
                }
                
                @Override
                public void mouseReleased(MouseEvent e) {
                    
                    
                }
                
                @Override
                public void mouseEntered(MouseEvent e) {
                    
                }
                
                @Override
                public void mouseExited(MouseEvent e) {
                    
                    
                }
                
            });
            ListaProveedores lprov = new ListaProveedores();
            lprov.setVisible(true);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbcproveedorActionPerformed

    private void jbproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproductoActionPerformed

        ListaProductos.whoisselected = "comprasproductos";        
        inst.getInstanciaListaProductos();
        
    }//GEN-LAST:event_jbproductoActionPerformed

    private void jbagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbagregarActionPerformed

        int id = Integer.parseInt(ListaProductos.jtproductos.getValueAt(ListaProductos.jtproductos.getSelectedRow(), 0).toString());
        String producto = ListaProductos.jtproductos.getValueAt(ListaProductos.jtproductos.getSelectedRow(), 1).toString();
        System.out.println(producto);
                
        DefaultTableModel dtm = (DefaultTableModel) jtagregar.getModel();
        
        String[] datos = {String.valueOf(id), producto, jtxtcantidad.getText(), 
            jtxtunidad.getText(), jtxtprecio.getText(), jtxtproveedor.getText()};
        dtm.addRow(datos);
        
        double t = 0;
        double p = 0;
        if(jtagregar.getRowCount() > 0){
            for(int i = 0; i < jtagregar.getRowCount(); i++){
                p = Double.parseDouble(jtagregar.getValueAt(i, 4).toString());
                t += p;
            }
            jltotal.setText(String.valueOf(t));          
            
            jtxtcantidad.setText("");
            jtxtunidad.setText("");
            jtxtproducto.setText("");
            jtxtobservaciones.setText("");
            jtxtprecio.setText("");  
            jchkcmostrador.setSelected(false);            
            jtxtticket.setEnabled(true);
            jtxtticket.setText("");
        }
        
    }//GEN-LAST:event_jbagregarActionPerformed

    private void jtproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtproductosMouseClicked

        
        
    }//GEN-LAST:event_jtproductosMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._compras = null;
        
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.dispose();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmi_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reporteActionPerformed

        try {
            rep.EmisionReporteDeCompras("/ReportesJasper/", "ReporteCompra.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmi_reporteActionPerformed

    private void jtxtbuscarcomprasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbuscarcomprasKeyReleased

        comp.muestraCompras(jtproductos, jtxtbuscarcompras.getText(), jdcfecha, 
                jdcfecha, Menu.idcompania);        
        comp.total(jtproductos, jtxttotal);
        
    }//GEN-LAST:event_jtxtbuscarcomprasKeyReleased

    private void jtagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtagregarMouseClicked

        _idproducto = Integer.parseInt(jtagregar.getValueAt(jtagregar.getSelectedRow(), 0).toString());
        jtxtproducto.setText(jtagregar.getValueAt(jtagregar.getSelectedRow(), 1).toString());
        jtxtcantidad.setText(jtagregar.getValueAt(jtagregar.getSelectedRow(), 2).toString());
        jtxtunidad.setText(jtagregar.getValueAt(jtagregar.getSelectedRow(), 3).toString());
        jtxtprecio.setText(jtagregar.getValueAt(jtagregar.getSelectedRow(), 4).toString());
        
    }//GEN-LAST:event_jtagregarMouseClicked

    private void jbsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbsalirMouseClicked

        Instancias._compras = null;
        this.dispose();
        
    }//GEN-LAST:event_jbsalirMouseClicked

    private void jchkcmostradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkcmostradorActionPerformed

        if(jchkcmostrador.isSelected() == true){
            jtxtticket.setEditable(false);
            cmostrador = "Mostrador";
        }else{
            jtxtticket.setEditable(true);
        }
        
    }//GEN-LAST:event_jchkcmostradorActionPerformed

    private void jtxtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbuscarKeyReleased

        comp.filtraCompras(jtagregar, jtxtbuscar.getText());
        
    }//GEN-LAST:event_jtxtbuscarKeyReleased

    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed

        try {
            rep.EmisionReporteDeCompras("/ReportesJasper/", "ReporteCompras.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbreporteActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtproductos);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        int row = jtagregar.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel)jtagregar.getModel();
        modelo.removeRow(row);
        jltotal.setText("");

        double t = 0;
        double p = 0;

       if(jtagregar.getRowCount() > 0){
            for(int i = 0; i < jtagregar.getRowCount(); i++){
                p = Double.parseDouble(jtagregar.getValueAt(i, 4).toString());
                t += p;
            }
            jltotal.setText(String.valueOf(t));
        }  
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        comp.jbcancelar(jtxtproveedor, jtxtticket, jtxtproducto, jtxtprecio, 
                jtxtcantidad, jtxtunidad, jtxtobservaciones, jdcfecha, jltotal);
        DefaultTableModel dtm = (DefaultTableModel) jtproductos.getModel();
        int a = jtproductos.getRowCount()-1;
        for(int i = a; i >= 0; i--){
            dtm.removeRow(dtm.getRowCount()-1);
        }
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        int idcompra_;
        if(jdcfecha.getDate() == null){
            jtm.jTextAreaMessage("Existen campos nulos");
        }else{
            System.out.println("Id Proveedor: "+idproveedor);
            if(jchkcmostrador.isSelected() == true){
                
                comp.jbguardar(idproveedor, 
                        jtxtproveedor.getText(), 
                        cmostrador, 
                        jtxtobservaciones.getText(), 
                        jdcfecha, 
                        Double.parseDouble(jltotal.getText()),
                        Menu.idusu,
                        Menu.idcompania);                
                idcompra_ = comp.obtenerCompra(Menu.idcompania);                    
                System.out.println("Id Compra: "+idcompra_);            
                
                for(int row = 0; row < jtagregar.getRowCount(); row++){
                    comp.jbguardarProductos(idcompra_, 
                            Integer.parseInt(jtagregar.getValueAt(row, 0).toString()), 
                            jtagregar.getValueAt(row, 1).toString(), 
                            Integer.parseInt(jtagregar.getValueAt(row, 2).toString()), 
                            jtagregar.getValueAt(row, 3).toString(),
                            Double.parseDouble(jtagregar.getValueAt(row, 4).toString()),
                            Menu.idusu,
                            Menu.idcompania);
                    }
                
                    comp.jbcancelar(jtxtproveedor, jtxtticket, jtxtproducto, jtxtprecio, 
                            jtxtcantidad, jtxtunidad, jtxtobservaciones, jdcfecha, jltotal);
                    
                    DefaultTableModel dtm = (DefaultTableModel) jtagregar.getModel();
                    int a = jtagregar.getRowCount()-1;
                    for(int i = a; i >= 0; i--){
                        dtm.removeRow(dtm.getRowCount()-1);
                    }
            }else{                
                comp.jbguardar(idproveedor, 
                        jtxtproveedor.getText(), 
                        jtxtticket.getText(), 
                        jtxtobservaciones.getText(), 
                        jdcfecha, 
                        Double.parseDouble(jltotal.getText()),
                        Menu.idusu,
                        Menu.idcompania);                        
                
                idcompra_ = comp.obtenerCompra(Menu.idcompania);                    
                System.out.println("Id Compra: "+idcompra_);                                         
                    
                for(int row = 0; row < jtagregar.getRowCount(); row++){
                    comp.jbguardarProductos(idcompra_, 
                            Integer.parseInt(jtagregar.getValueAt(row, 0).toString()), 
                            jtagregar.getValueAt(row, 1).toString(), 
                            Integer.parseInt(jtagregar.getValueAt(row, 2).toString()), 
                            jtagregar.getValueAt(row, 3).toString(),
                            Double.parseDouble(jtagregar.getValueAt(row, 4).toString()),
                            Menu.idusu,
                            Menu.idcompania);
                    }
                
                comp.jbcancelar(jtxtproveedor, jtxtticket, jtxtproducto, jtxtprecio, 
                    jtxtcantidad, jtxtunidad, jtxtobservaciones, jdcfecha, jltotal);
                
                DefaultTableModel dtm = (DefaultTableModel) jtagregar.getModel();
                int a = jtagregar.getRowCount()-1;
                for(int i = a; i >= 0; i--){
                    dtm.removeRow(dtm.getRowCount()-1);
               }                    
            }
            comp.muestraCompras(jtproductos, "", jdcfecha, jdcfecha, Menu.idcompania);  
        }        
        
    }//GEN-LAST:event_jbguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Compras().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbagregar;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbcproveedor;
    public static javax.swing.JButton jbeliminar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jbproducto;
    public static javax.swing.JButton jbreporte;
    private javax.swing.JButton jbsalir;
    private javax.swing.JCheckBox jchkcmostrador;
    private com.toedter.calendar.JDateChooser jdcfecha;
    private javax.swing.JTextField jltotal;
    public static javax.swing.JMenu jmacciones;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_eliminar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenuItem jmi_reporte;
    public static javax.swing.JMenu jmreportes;
    private javax.swing.JTable jtagregar;
    private javax.swing.JTable jtproductos;
    private javax.swing.JTextField jtxtbuscar;
    private javax.swing.JTextField jtxtbuscarcompras;
    private javax.swing.JTextField jtxtcantidad;
    private javax.swing.JTextArea jtxtobservaciones;
    private javax.swing.JTextField jtxtprecio;
    public static javax.swing.JTextField jtxtproducto;
    public static javax.swing.JTextField jtxtproveedor;
    private javax.swing.JTextField jtxtticket;
    private javax.swing.JTextField jtxttotal;
    private javax.swing.JTextField jtxtunidad;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}
