/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Compras;

import C.Compras.ajusteprecios;
import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import Frames.Listados.ListaProductos;
import Frames.Menu;
import ReportesJasper.reportes;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author jraraujo
 */
public class EdicionPrecios extends javax.swing.JFrame {

    Image img;
    ajusteprecios ajp = new ajusteprecios();
    public static int idproducto;
    int idcompra, idcompra_producto;
    String ajuste;
    JTextAreaMessages jtm = new JTextAreaMessages();
    Instancias inst = new Instancias();
    reportes rep = new reportes();
    CheckAccess chk = new CheckAccess();
    JTableHeader th;
    /**
     * Creates new form EdicionPrecios
     */
    public EdicionPrecios() {
        initComponents();
        this.setLocationRelativeTo(null);
        jtproductos.setDefaultEditor(Object.class, null);
        th = jtproductos.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        chk.revisarAccesosEdicionPrecios(Menu.idusu);
        ajp.muestraProductos(jtproductos, "", Menu.idcompania);
        jdcfecha.setDateFormatString("yyyy-MM-dd");
        jdcfecha.setDate(new Date());
        ajp.total(jtproductos, jtxttotal);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbmodificar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        jtxtbuscar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jbsalir = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtproductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtxttotal = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtrazonajuste = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jtxtcantidadajuste = new javax.swing.JTextField();
        jckajuste = new javax.swing.JCheckBox();
        jdcfecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtidcompraproducto = new javax.swing.JTextField();
        jbajustes = new javax.swing.JButton();
        jbactualizar = new javax.swing.JButton();
        jbproducto = new javax.swing.JButton();
        jtxtidproducto = new javax.swing.JTextField();
        jtxtproducto = new javax.swing.JTextField();
        jtxtcantidad = new javax.swing.JTextField();
        jtxtunidad = new javax.swing.JTextField();
        jtxtprecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmacciones = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmajustes = new javax.swing.JMenu();
        jmi_ajustes = new javax.swing.JMenuItem();
        jmi_modajustes = new javax.swing.JMenuItem();
        jmreportes = new javax.swing.JMenu();
        jmi_reportecompras = new javax.swing.JMenuItem();
        jmi_reporteajustes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Ajuste de Precios]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setEnabled(false);
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator1);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setBorderPainted(false);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setEnabled(false);
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator2);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setEnabled(false);
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator3);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setBorder(null);
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.setEnabled(false);
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator5);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setEnabled(false);
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator9);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setBorder(null);
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setEnabled(false);
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator10);

        jLabel4.setText("Buscar:");
        jToolBar1.add(jLabel4);
        jToolBar1.add(jtxtbuscar);
        jToolBar1.add(jSeparator6);

        jbsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jbsalir.setBorder(null);
        jbsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbsalir.setFocusable(false);
        jbsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsalirMouseClicked(evt);
            }
        });
        jToolBar1.add(jbsalir);
        jToolBar1.add(jSeparator7);

        jtproductos.setAutoCreateRowSorter(true);
        jtproductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtproductos.setForeground(new java.awt.Color(0, 153, 153));
        jtproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdCompras_ Producto", "Id Compra", "Id Producto", "Producto", "Cantidad", "unidad", "Precio", "Id Empleado", "Id Empresa"
            }
        ));
        jtproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtproductos);

        jPanel3.setBackground(Color.decode("#C70039"));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total   $:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(Color.decode("#C70039"));

        jPanel4.setOpaque(false);

        jPanel2.setBackground(Color.decode("#A80030"));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Razón del ajuste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jtxtrazonajuste.setColumns(20);
        jtxtrazonajuste.setLineWrap(true);
        jtxtrazonajuste.setRows(5);
        jtxtrazonajuste.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jtxtrazonajuste);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad del Ajuste:");

        jckajuste.setForeground(new java.awt.Color(255, 255, 255));
        jckajuste.setText("Positivo");
        jckajuste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jckajuste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jckajuste.setOpaque(false);
        jckajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckajusteActionPerformed(evt);
            }
        });

        jdcfecha.setDateFormatString("yyyy-MM-dd");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha ajuste");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Id Compra Producto");

        jtxtidcompraproducto.setEditable(false);

        jbajustes.setText("Ajustes");
        jbajustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbajustes.setEnabled(false);
        jbajustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbajustesActionPerformed(evt);
            }
        });

        jbactualizar.setText("Actualizar Ajuste");
        jbactualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbactualizar.setEnabled(false);
        jbactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtidcompraproducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jbajustes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jckajuste, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdcfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addComponent(jtxtcantidadajuste)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbactualizar)))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtcantidadajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jckajuste, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdcfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbactualizar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbajustes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtidcompraproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbproducto.setText("Producto:");
        jbproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbproducto.setEnabled(false);
        jbproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbproductoActionPerformed(evt);
            }
        });

        jtxtidproducto.setEditable(false);

        jtxtprecio.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Precio:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Unidad:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cantidad:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxtcantidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addComponent(jtxtprecio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtunidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtidproducto)
                            .addComponent(jbproducto)
                            .addComponent(jtxtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtprecio)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel1.add(jPanel4);

        jTabbedPane1.addTab("Edición de Productos y Precios", jPanel1);

        jmacciones.setText("Acciones");
        jmacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmacciones.setEnabled(false);

        jmi_guardar.setText("Guardar");
        jmi_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_guardar.setEnabled(false);
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_cancelar.setEnabled(false);
        jmi_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cancelarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_cancelar);

        jmi_eliminar.setText("Eiminar");
        jmi_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_eliminar.setEnabled(false);
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_eliminar);

        jmi_modificar.setText("Modificar");
        jmi_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_modificar.setEnabled(false);
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_modificar);

        jmi_exportar.setText("Exportar");
        jmi_exportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_exportar.setEnabled(false);
        jmi_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_exportarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_exportar);
        jmacciones.add(jSeparator8);

        jMenuItem5.setText("Salir");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmacciones.add(jMenuItem5);

        jMenuBar1.add(jmacciones);

        jmajustes.setText("Ajustes");
        jmajustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmajustes.setEnabled(false);

        jmi_ajustes.setText("Ajustes");
        jmi_ajustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_ajustes.setEnabled(false);
        jmi_ajustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ajustesActionPerformed(evt);
            }
        });
        jmajustes.add(jmi_ajustes);

        jmi_modajustes.setText("Actualizar Ajuste");
        jmi_modajustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_modajustes.setEnabled(false);
        jmi_modajustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modajustesActionPerformed(evt);
            }
        });
        jmajustes.add(jmi_modajustes);

        jMenuBar1.add(jmajustes);

        jmreportes.setText("Reportes");
        jmreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmreportes.setEnabled(false);

        jmi_reportecompras.setText("Edicion de Precios");
        jmi_reportecompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_reportecompras.setEnabled(false);
        jmi_reportecompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reportecomprasActionPerformed(evt);
            }
        });
        jmreportes.add(jmi_reportecompras);

        jmi_reporteajustes.setText("Ajustes");
        jmi_reporteajustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_reporteajustes.setEnabled(false);
        jmi_reporteajustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reporteajustesActionPerformed(evt);
            }
        });
        jmreportes.add(jmi_reporteajustes);

        jMenuBar1.add(jmreportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtproductosMouseClicked

        idcompra_producto = Integer.parseInt(jtproductos.getValueAt(jtproductos.getSelectedRow(), 0).toString());
        idcompra = Integer.parseInt(jtproductos.getValueAt(jtproductos.getSelectedRow(), 1).toString());
        jtxtidproducto.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 2).toString());
        jtxtproducto.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 3).toString());
        jtxtcantidad.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 4).toString());
        jtxtunidad.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 5).toString());
        jtxtprecio.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 6).toString());
        
    }//GEN-LAST:event_jtproductosMouseClicked

    private void jbproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproductoActionPerformed

       ListaProductos.whoisselected = "edicionproducto";
       inst.getInstanciaListaProductos();
        
    }//GEN-LAST:event_jbproductoActionPerformed

    private void jckajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckajusteActionPerformed

        if(jckajuste.isSelected() == true){
            ajuste = "Positivo";
            System.out.println(ajuste);
        }else{
            ajuste = "Negativo";
            System.out.println(ajuste);
        }       
        
    }//GEN-LAST:event_jckajusteActionPerformed

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed

         if(jtxtproducto.getText().equals("") || jtxtcantidad.getText().equals("") 
                || jtxtunidad.getText().equals("") || jtxtprecio.getText().equals("")
                || jtxtrazonajuste.getText().equals("") || jtxtcantidadajuste.getText().equals("") 
                || jdcfecha.getDate() == null){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            ajp.jbguardar(Integer.parseInt(jtxtidproducto.getText()), jtxtproducto.getText(), 
                    Integer.parseInt(jtxtcantidad.getText()), jtxtunidad.getText(), 
                    Double.parseDouble(jtxtprecio.getText()), idcompra_producto,
                    Menu.idusu, Menu.idcompania);

            ajp.ajusteCompras(jtxtrazonajuste.getText(), Double.parseDouble(jtxtcantidadajuste.getText()), 
                    ajuste, jdcfecha, Menu.idusu, Menu.idcompania);
            
            ajp.jbcancelar(jtxtidproducto, jtxtproducto, jtxtcantidad, jtxtunidad, 
                    jtxtprecio, jtxtrazonajuste, jtxtcantidadajuste, jckajuste, jdcfecha);
            
            ajp.muestraProductos(jtproductos, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jmi_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cancelarActionPerformed

        ajp.jbcancelar(jtxtidproducto, jtxtproducto, jtxtcantidad, jtxtunidad, 
                    jtxtprecio, jtxtrazonajuste, jtxtcantidadajuste, jckajuste, jdcfecha);
         ajp.muestraProductos(jtproductos, "", Menu.idcompania);
         ajp.total(jtproductos, jtxttotal);
        
    }//GEN-LAST:event_jmi_cancelarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed

       if(String.valueOf(idcompra_producto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado compra");
        }else{
            ajp.jbeliminar(idcompra_producto, Menu.idcompania);
            ajp.jbcancelar(jtxtidproducto, jtxtproducto, jtxtcantidad, jtxtunidad, jtxtprecio, 
                    jtxtrazonajuste, jtxtcantidadajuste, jckajuste, jdcfecha);
            ajp.muestraProductos(jtproductos, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jbajustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbajustesActionPerformed

        inst.getInstanciaAjustes();
        
    }//GEN-LAST:event_jbajustesActionPerformed

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed

        if(String.valueOf(idcompra_producto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado compra");
        }else{
            ajp.jbmodificar(Integer.parseInt(jtxtidproducto.getText()), 
                    jtxtproducto.getText(),
                    Integer.parseInt(jtxtcantidad.getText()), 
                    jtxtunidad.getText(), 
                    Double.parseDouble(jtxtprecio.getText()), 
                    idcompra_producto,
                    Menu.idusu,
                    Menu.idcompania);            
            ajp.jbcancelar(jtxtidproducto, jtxtproducto, jtxtcantidad, jtxtunidad, jtxtprecio, 
                    jtxtrazonajuste, jtxtcantidadajuste, jckajuste, jdcfecha);
            ajp.muestraProductos(jtproductos, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        this.dispose();
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmi_ajustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ajustesActionPerformed

        ConsultaAjustes aju = new ConsultaAjustes();
        aju.setVisible(true);
        
    }//GEN-LAST:event_jmi_ajustesActionPerformed

    private void jmi_modajustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modajustesActionPerformed

        if(String.valueOf(idcompra_producto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un ajuste");
        }else{
            ajp.jbmodificarAjustes(jtxtrazonajuste.getText(), 
                    Double.parseDouble(jtxtcantidadajuste.getText()),
                        ajuste, 
                        jdcfecha, 
                        Integer.parseInt(jtxtidcompraproducto.getText()),
                        Menu.idusu,
                        Menu.idcompania);
            ajp.jbcancelarAjuste(jtxtidcompraproducto, jtxtrazonajuste, 
                    jtxtcantidadajuste, jckajuste, jdcfecha);        
        }
        
    }//GEN-LAST:event_jmi_modajustesActionPerformed

    private void jmi_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_exportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtproductos);
        
    }//GEN-LAST:event_jmi_exportarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._edicionprecios = null;
        
    }//GEN-LAST:event_formWindowClosing

    private void jbsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbsalirMouseClicked

        Instancias._edicionprecios = null;
        this.dispose();
        
    }//GEN-LAST:event_jbsalirMouseClicked

    private void jbactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbactualizarActionPerformed

        if(String.valueOf(idcompra_producto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un ajuste");
        }else{
            ajp.jbmodificarAjustes(jtxtrazonajuste.getText(), 
                    Double.parseDouble(jtxtcantidadajuste.getText()),
                        ajuste, 
                        jdcfecha, 
                        Integer.parseInt(jtxtidcompraproducto.getText()),
                        Menu.idusu,
                        Menu.idcompania);
            ajp.jbcancelarAjuste(jtxtidcompraproducto, jtxtrazonajuste, 
                    jtxtcantidadajuste, jckajuste, jdcfecha);        
        }
        
    }//GEN-LAST:event_jbactualizarActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

         f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtproductos);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        if(String.valueOf(idcompra_producto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado compra");
        }else{
            ajp.jbmodificar(Integer.parseInt(jtxtidproducto.getText()), 
                    jtxtproducto.getText(),
                    Integer.parseInt(jtxtcantidad.getText()), 
                    jtxtunidad.getText(), 
                    Double.parseDouble(jtxtprecio.getText()), 
                    idcompra_producto,
                    Menu.idusu,
                    Menu.idcompania);            
            ajp.jbcancelar(jtxtidproducto, jtxtproducto, jtxtcantidad, jtxtunidad, jtxtprecio, 
                    jtxtrazonajuste, jtxtcantidadajuste, jckajuste, jdcfecha);
            ajp.muestraProductos(jtproductos, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        if(String.valueOf(idcompra_producto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado compra");
        }else{
            ajp.jbeliminar(idcompra_producto, Menu.idcompania);
            ajp.jbcancelar(jtxtidproducto, jtxtproducto, jtxtcantidad, jtxtunidad, jtxtprecio, 
                    jtxtrazonajuste, jtxtcantidadajuste, jckajuste, jdcfecha);
            ajp.muestraProductos(jtproductos, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

         ajp.jbcancelar(jtxtidproducto, jtxtproducto, jtxtcantidad, jtxtunidad, 
                    jtxtprecio, jtxtrazonajuste, jtxtcantidadajuste, jckajuste, jdcfecha);
         ajp.muestraProductos(jtproductos, "", Menu.idcompania);
         ajp.total(jtproductos, jtxttotal);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        if(jtxtproducto.getText().equals("") || jtxtcantidad.getText().equals("") 
                || jtxtunidad.getText().equals("") || jtxtprecio.getText().equals("")
                || jtxtrazonajuste.getText().equals("") || jtxtcantidadajuste.getText().equals("") 
                || jdcfecha.getDate() == null){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            ajp.jbguardar(Integer.parseInt(jtxtidproducto.getText()), 
                    jtxtproducto.getText(), 
                    Integer.parseInt(jtxtcantidad.getText()), 
                    jtxtunidad.getText(), 
                    Double.parseDouble(jtxtprecio.getText()), 
                    idcompra_producto,
                    Menu.idusu,
                    Menu.idcompania);

            ajp.ajusteCompras(jtxtrazonajuste.getText(), 
                    Double.parseDouble(jtxtcantidadajuste.getText()), 
                    ajuste, 
                    jdcfecha, 
                    Menu.idusu, 
                    Menu.idcompania);
            
            ajp.jbcancelar(jtxtidproducto, jtxtproducto, jtxtcantidad, jtxtunidad, 
                    jtxtprecio, jtxtrazonajuste, jtxtcantidadajuste, jckajuste, jdcfecha);
            
            ajp.muestraProductos(jtproductos, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jmi_reporteajustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reporteajustesActionPerformed

         try {
            rep.EmisionReporteEdicionPrecios("/ReportesJasper/", "ReporteAjustes.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(EdicionPrecios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmi_reporteajustesActionPerformed

    private void jmi_reportecomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reportecomprasActionPerformed

         try {
            rep.EmisionReporteEdicionPrecios("/ReportesJasper/", "ReporteEdicionPrecios.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(EdicionPrecios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmi_reportecomprasActionPerformed

    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed

        inst.getInstanciasReportesCompras();
        
    }//GEN-LAST:event_jbreporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EdicionPrecios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbactualizar;
    public static javax.swing.JButton jbajustes;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbeliminar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jbmodificar;
    public static javax.swing.JButton jbproducto;
    public static javax.swing.JButton jbreporte;
    private javax.swing.JButton jbsalir;
    public static javax.swing.JCheckBox jckajuste;
    public static com.toedter.calendar.JDateChooser jdcfecha;
    public static javax.swing.JMenu jmacciones;
    public static javax.swing.JMenu jmajustes;
    public static javax.swing.JMenuItem jmi_ajustes;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_eliminar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenuItem jmi_modajustes;
    public static javax.swing.JMenuItem jmi_modificar;
    public static javax.swing.JMenuItem jmi_reporteajustes;
    public static javax.swing.JMenuItem jmi_reportecompras;
    public static javax.swing.JMenu jmreportes;
    private javax.swing.JTable jtproductos;
    private javax.swing.JTextField jtxtbuscar;
    public static javax.swing.JTextField jtxtcantidad;
    public static javax.swing.JTextField jtxtcantidadajuste;
    public static javax.swing.JTextField jtxtidcompraproducto;
    public static javax.swing.JTextField jtxtidproducto;
    public static javax.swing.JTextField jtxtprecio;
    public static javax.swing.JTextField jtxtproducto;
    public static javax.swing.JTextArea jtxtrazonajuste;
    private javax.swing.JTextField jtxttotal;
    public static javax.swing.JTextField jtxtunidad;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}

