/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Parametros;

import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import C.Licencia.licencia;
import C.Parametros.datosempresa;
import UUID.uuid;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jraraujo
 */
public class DatosEmpresa extends javax.swing.JFrame {
    datosempresa datos = new datosempresa();
    JTextAreaMessages jtm = new JTextAreaMessages();
    public static int idempresa;
    JTableHeader th;
    Instancias inst = new Instancias();
    /**
     * Creates new form DatosEmpresa
     */
    public DatosEmpresa() {
        initComponents();
        this.setLocationRelativeTo(null);
        jtempresas.setDefaultEditor(Object.class, null);
        th = jtempresas.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        datos.mostrarEmpresas(jtempresas);
//        if(Menu.rol_login.equals("adm")){
//            this.jbcancelar.setEnabled(true);
//            this.jbeliminar.setEnabled(true);
//            this.jbexportar.setEnabled(true);
//            this.jbmodificar.setEnabled(true);
//            this.jbguardar.setEnabled(true);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtrazon = new javax.swing.JTextField();
        jtxtrfc = new javax.swing.JTextField();
        jtxtpais = new javax.swing.JTextField();
        jtxtestado = new javax.swing.JTextField();
        jtxtmunicipio = new javax.swing.JTextField();
        jtxtcolonia = new javax.swing.JTextField();
        jtxtdireccion = new javax.swing.JTextField();
        jtxtnoext = new javax.swing.JTextField();
        jtxtnoint = new javax.swing.JTextField();
        jtxttelefono = new javax.swing.JTextField();
        jtxtcorreo = new javax.swing.JTextField();
        jtxtpagina = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtcodpos = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jbmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtempresas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiguardar = new javax.swing.JMenuItem();
        jmicancelar = new javax.swing.JMenuItem();
        jmieliminar = new javax.swing.JMenuItem();
        jmimodificar = new javax.swing.JMenuItem();
        jmiexportar = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jmisalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmireporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Empresas]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBackground(Color.decode("#C70039"));

        jPanel1.setBackground(Color.decode("#C70039"));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jPanel2.setBackground(Color.decode("#C70039"));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Razon Social:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RFC:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pais:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estado:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Muicipio:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Colonia:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dirección");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("No. Ext:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("No. Int:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Teléfono:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Correo:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Página:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cod. Postal:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtrazon)
                    .addComponent(jtxtrfc)
                    .addComponent(jtxtpais)
                    .addComponent(jtxtestado)
                    .addComponent(jtxtmunicipio)
                    .addComponent(jtxtcolonia)
                    .addComponent(jtxtdireccion)
                    .addComponent(jtxtnoext)
                    .addComponent(jtxtnoint)
                    .addComponent(jtxttelefono)
                    .addComponent(jtxtcorreo)
                    .addComponent(jtxtpagina)
                    .addComponent(jtxtcodpos, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtrazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtrfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtcolonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtnoext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtnoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtcodpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtpagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos de Empresa", jPanel1);

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator6);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator5);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator4);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setBorder(null);
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator3);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator2);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setBorder(null);
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator1);

        jbsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jbsalir.setBorder(null);
        jbsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbsalir.setFocusable(false);
        jbsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbsalir);

        jtempresas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtempresas.setForeground(new java.awt.Color(0, 102, 102));
        jtempresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Empresa", "Razón Social", "RFC", "País", "Estado", "Muicipio", "Colonia", "Dirección", "No. Ext", "No. Int", "Codigo Postal", "Teléfono", "Correo", "Pagina"
            }
        ));
        jtempresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtempresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtempresas);

        jMenuBar1.setBackground(Color.decode("#C70039"));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Acciones");

        jmiguardar.setText("Guardar");
        jmiguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiguardarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiguardar);

        jmicancelar.setText("Cancelar");
        jmicancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmicancelarActionPerformed(evt);
            }
        });
        jMenu1.add(jmicancelar);

        jmieliminar.setText("Eliminar");
        jmieliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmieliminarActionPerformed(evt);
            }
        });
        jMenu1.add(jmieliminar);

        jmimodificar.setText("Modificar");
        jmimodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmimodificarActionPerformed(evt);
            }
        });
        jMenu1.add(jmimodificar);

        jmiexportar.setText("Exportar");
        jmiexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiexportarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiexportar);
        jMenu1.add(jSeparator7);

        jmisalir.setText("Salir");
        jmisalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmisalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmisalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Reporte");

        jmireporte.setText("Reporte");
        jMenu2.add(jmireporte);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        if(jtxtrazon.getText().equals("") 
                || jtxtrfc.getText().equals("")
                || jtxtpais.getText().equals("")
                || jtxtestado.getText().equals("")
                || jtxtmunicipio.getText().equals("")
                || jtxtcolonia.getText().equals("")
                || jtxtdireccion.getText().equals("")
                || jtxtcodpos.getText().equals("")
                ||jtxtdireccion.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            datos.registraProducto(jtxtrazon.getText(), jtxtrfc.getText(), 
                    uuid.OS, 
                    uuid.HDWR, 
                    uuid.PROCESSORSN, 
                    uuid.PROCESSORID, 
                    String.valueOf(uuid.processors), 
                    licencia._LICENCIA, 
                    1);
            if(datos.obtenRFC(idempresa).equals("")){
                datos.jbguardar(jtxtrazon.getText(), jtxtrfc.getText(), jtxtpais.getText(), 
                    jtxtestado.getText(), jtxtmunicipio.getText(), jtxtcolonia.getText(), 
                    jtxtdireccion.getText(), jtxtnoext.getText(), jtxtnoint.getText(), 
                    jtxtcodpos.getText(), jtxttelefono.getText(), jtxtcorreo.getText(), 
                    jtxtpagina.getText());
                datos.jbcancelar(jtxtrazon, jtxtrfc, jtxtpais, jtxtestado, jtxtmunicipio, 
                        jtxtcolonia, jtxtdireccion, jtxtnoext, jtxtnoint, jtxtcodpos, 
                        jtxttelefono, jtxtcorreo, jtxtpagina);
                datos.mostrarEmpresas(jtempresas);
            }else{
                try {
                    inst.getInstanciasSplashInicio();
                } catch (InterruptedException | ClassNotFoundException ex) {
                    Logger.getLogger(DatosEmpresa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }          
        }        
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        datos.jbcancelar(jtxtrazon, jtxtrfc, jtxtpais, jtxtestado, jtxtmunicipio, 
                jtxtcolonia, jtxtdireccion, jtxtnoext, jtxtnoint, jtxtcodpos, 
                jtxttelefono, jtxtcorreo, jtxtpagina);
        datos.mostrarEmpresas(jtempresas);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        if(String.valueOf(idempresa).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado una empresa");
        }else{
            datos.jbeliminar(idempresa);
            datos.jbcancelar(jtxtrazon, jtxtrfc, jtxtpais, jtxtestado, jtxtmunicipio, 
                    jtxtcolonia, jtxtdireccion, jtxtnoext, jtxtnoint, jtxtcodpos, 
                    jtxttelefono, jtxtcorreo, jtxtpagina);
            datos.mostrarEmpresas(jtempresas);
        }
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        if(String.valueOf(idempresa).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado una empresa");
        }else{
            datos.jbmodificar(jtxtrazon.getText(), jtxtrfc.getText(), jtxtpais.getText(), 
                        jtxtestado.getText(), jtxtmunicipio.getText(), jtxtcolonia.getText(), 
                        jtxtdireccion.getText(), jtxtnoext.getText(), jtxtnoint.getText(), 
                        jtxtcodpos.getText(), jtxttelefono.getText(), jtxtcorreo.getText(), 
                        jtxtpagina.getText(), idempresa);
         }
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtempresas);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed

        Instancias._datosempresa = null;
        this.dispose();
        
    }//GEN-LAST:event_jbsalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._datosempresa = null;
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosing

    private void jtempresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtempresasMouseClicked

        idempresa = Integer.parseInt(jtempresas.getValueAt(jtempresas.getSelectedRow(), 0).toString());
        jtxtrazon.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 1).toString());
        jtxtrfc.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 2).toString());
        jtxtpais.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 3).toString());
        jtxtestado.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 4).toString());
        jtxtmunicipio.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 5).toString());
        jtxtcolonia.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 6).toString());
        jtxtdireccion.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 7).toString());
        jtxtnoext.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 8).toString());
        jtxtnoint.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 9).toString());
        jtxtcodpos.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 10).toString());
        jtxttelefono.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 11).toString());
        jtxtcorreo.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 12).toString());
        jtxtpagina.setText(jtempresas.getValueAt(jtempresas.getSelectedRow(), 13).toString());       
        
    }//GEN-LAST:event_jtempresasMouseClicked

    private void jmiguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiguardarActionPerformed

         if(jtxtrazon.getText().equals("") 
                || jtxtrfc.getText().equals("")
                || jtxtpais.getText().equals("")
                || jtxtestado.getText().equals("")
                || jtxtmunicipio.getText().equals("")
                || jtxtcolonia.getText().equals("")
                || jtxtdireccion.getText().equals("")
                || jtxtcodpos.getText().equals("")
                ||jtxtdireccion.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            datos.jbguardar(jtxtrazon.getText(), jtxtrfc.getText(), jtxtpais.getText(), 
                    jtxtestado.getText(), jtxtmunicipio.getText(), jtxtcolonia.getText(), 
                    jtxtdireccion.getText(), jtxtnoext.getText(), jtxtnoint.getText(), 
                    jtxtcodpos.getText(), jtxttelefono.getText(), jtxtcorreo.getText(), 
                    jtxtpagina.getText());
            datos.jbcancelar(jtxtrazon, jtxtrfc, jtxtpais, jtxtestado, jtxtmunicipio, 
                    jtxtcolonia, jtxtdireccion, jtxtnoext, jtxtnoint, jtxtcodpos, 
                    jtxttelefono, jtxtcorreo, jtxtpagina);
            datos.mostrarEmpresas(jtempresas);
        }        
        
    }//GEN-LAST:event_jmiguardarActionPerformed

    private void jmicancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmicancelarActionPerformed

         datos.jbcancelar(jtxtrazon, jtxtrfc, jtxtpais, jtxtestado, jtxtmunicipio, 
                jtxtcolonia, jtxtdireccion, jtxtnoext, jtxtnoint, jtxtcodpos, 
                jtxttelefono, jtxtcorreo, jtxtpagina);
        datos.mostrarEmpresas(jtempresas);
        
    }//GEN-LAST:event_jmicancelarActionPerformed

    private void jmieliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmieliminarActionPerformed

        if(String.valueOf(idempresa).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado una empresa");
        }else{
            datos.jbeliminar(idempresa);
            datos.jbcancelar(jtxtrazon, jtxtrfc, jtxtpais, jtxtestado, jtxtmunicipio, 
                    jtxtcolonia, jtxtdireccion, jtxtnoext, jtxtnoint, jtxtcodpos, 
                    jtxttelefono, jtxtcorreo, jtxtpagina);
            datos.mostrarEmpresas(jtempresas);
        }
        
    }//GEN-LAST:event_jmieliminarActionPerformed

    private void jmimodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmimodificarActionPerformed

        if(String.valueOf(idempresa).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado una empresa");
        }else{
            datos.jbmodificar(jtxtrazon.getText(), jtxtrfc.getText(), jtxtpais.getText(), 
                        jtxtestado.getText(), jtxtmunicipio.getText(), jtxtcolonia.getText(), 
                        jtxtdireccion.getText(), jtxtnoext.getText(), jtxtnoint.getText(), 
                        jtxtcodpos.getText(), jtxttelefono.getText(), jtxtcorreo.getText(), 
                        jtxtpagina.getText(), idempresa);
         }
        
    }//GEN-LAST:event_jmimodificarActionPerformed

    private void jmiexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtempresas);
        
    }//GEN-LAST:event_jmiexportarActionPerformed

    private void jmisalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmisalirActionPerformed

        Instancias._datosempresa = null;
        this.dispose();
        
    }//GEN-LAST:event_jmisalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DatosEmpresa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbexportar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JButton jbreporte;
    private javax.swing.JButton jbsalir;
    private javax.swing.JMenuItem jmicancelar;
    private javax.swing.JMenuItem jmieliminar;
    private javax.swing.JMenuItem jmiexportar;
    private javax.swing.JMenuItem jmiguardar;
    private javax.swing.JMenuItem jmimodificar;
    private javax.swing.JMenuItem jmireporte;
    private javax.swing.JMenuItem jmisalir;
    private javax.swing.JTable jtempresas;
    private javax.swing.JTextField jtxtcodpos;
    private javax.swing.JTextField jtxtcolonia;
    private javax.swing.JTextField jtxtcorreo;
    private javax.swing.JTextField jtxtdireccion;
    private javax.swing.JTextField jtxtestado;
    private javax.swing.JTextField jtxtmunicipio;
    private javax.swing.JTextField jtxtnoext;
    private javax.swing.JTextField jtxtnoint;
    private javax.swing.JTextField jtxtpagina;
    private javax.swing.JTextField jtxtpais;
    private javax.swing.JTextField jtxtrazon;
    private javax.swing.JTextField jtxtrfc;
    private javax.swing.JTextField jtxttelefono;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    } 
}
