/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Ventas;

import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Ventas.ventas;
import Frames.Listados.ListaProductos;
import Frames.Menu;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jraraujo
 */
public class Ventas extends javax.swing.JFrame {
   
    String forma_pago="";
    int width, height;
    String fecha;
    Timer timer;
    JTextAreaMessages jtm = new JTextAreaMessages();
    public static JButton whosSelected;
    ventas ven = new ventas();   
    Instancias inst = new Instancias();
    JTableHeader th;  
    JTextPane jtpane;
    
    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();        
        this.setLocationRelativeTo(null);
        timer = new Timer(1000, new Ventas.cronometro());
        timer.start();
        th = jtableventas.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        jtableventas.setDefaultEditor(Object.class, null);       
    }
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnsaldar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnaniadir = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnmiscelaneos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableventas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jrefectivo = new javax.swing.JRadioButton();
        jrtarjeta = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxttotal = new javax.swing.JTextField();
        jtxtcambio = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtxtidventa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtfecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxthora = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari [Registro de Ventas]");
        setIconImage(getIconImage());
        setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, 710));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnsaldar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        btnsaldar.setText("<html><head><br><br><br>Saldar</head><html>");
        btnsaldar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsaldar.setEnabled(false);
        btnsaldar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaldarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        btneliminar.setText("<html><head><br><br><br>Remover</head><html>");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.setEnabled(false);
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnaniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnaniadir.setText("<html><head><br><br><br>Añadir</head><html>");
        btnaniadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaniadir.setEnabled(false);
        btnaniadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnaniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaniadirActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        btnsalir.setText("<html><head><br><br><br>Salir</head><html>");
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new.png"))); // NOI18N
        btnnuevo.setText("<html><head><br><br><br>Nuevo</head><html>");
        btnnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        btncancelar.setText("<html><head><br><br><br>Cancelar</head><html>");
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar.setEnabled(false);
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnmiscelaneos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/miscelaneo.png"))); // NOI18N
        btnmiscelaneos.setText("<html><head><br><br><br>Miscelaneo</head><html>");
        btnmiscelaneos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmiscelaneos.setEnabled(false);
        btnmiscelaneos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmiscelaneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmiscelaneosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsaldar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaniadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmiscelaneos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaniadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmiscelaneos)
                .addGap(14, 14, 14)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsaldar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width-115,
            Toolkit.getDefaultToolkit().getScreenSize().height-152));

    jtableventas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 0, 57)));
    jtableventas.setForeground(new java.awt.Color(0, 102, 102));
    jtableventas.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Id", "Producto", "Descripción", "Precio"
        }
    ));
    jScrollPane1.setViewportView(jtableventas);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
    );

    jPanel6.setBackground(new java.awt.Color(255, 255, 255));

    buttonGroup.add(jrefectivo);
    jrefectivo.setText("Efectivo:");
    jrefectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jrefectivo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jrefectivoActionPerformed(evt);
        }
    });

    buttonGroup.add(jrtarjeta);
    jrtarjeta.setText("Tarjeta:");
    jrtarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jrtarjeta.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jrtarjetaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jrefectivo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jrtarjeta)
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jrefectivo)
                .addComponent(jrtarjeta))
            .addGap(138, 138, 138))
    );

    jPanel7.setBackground(Color.decode("#C70039"));
    jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Total:");

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Cambio:");

    jtxttotal.setEditable(false);
    jtxttotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jtxttotal.setForeground(new java.awt.Color(0, 153, 0));

    jtxtcambio.setEditable(false);
    jtxtcambio.setBackground(new java.awt.Color(255, 204, 0));
    jtxtcambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jtxtcambio.setForeground(new java.awt.Color(204, 0, 0));

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jtxtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(jtxtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel8.setBackground(Color.decode("#C70039"));

    jLabel8.setBackground(new java.awt.Color(255, 255, 255));
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Venta:");

    jtxtidventa.setEditable(false);

    jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel9.setText("Fecha:");

    jtxtfecha.setEditable(false);

    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Hora:");

    jtxthora.setEditable(false);

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(jtxtidventa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jtxtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jtxthora, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jtxtidventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9)
                .addComponent(jtxtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6)
                .addComponent(jtxthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed

        Instancias._ventas = null;
        this.dispose();
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnaniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaniadirActionPerformed

        ListaProductos.whoisselected = "ventasaniadir";
        inst.getInstanciaListaProductos();
                
    }//GEN-LAST:event_btnaniadirActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        try {        
            ven.verificarCaja();
            if(ven.verificarCaja() == false){
                Object opciones[]={"Aceptar","Cancelar"};
                int mensaje = JOptionPane.showOptionDialog(null, "No se ha registrado caja, "
                        + "¿Deseas continuar con la venta?","Fenix POS[Mensaje]", 
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, 
                        null, opciones, opciones[0]);
                if(mensaje == JOptionPane.OK_OPTION){
                    btnaniadir.setEnabled(true);
                    this.btneliminar.setEnabled(true);
                    this.btnsaldar.setEnabled(true);
                    this.btncancelar.setEnabled(true);
                    this.btnnuevo.setEnabled(false);
                    btnmiscelaneos.setEnabled(true);
                    ven.btn_nuevo(jtxtidventa);
                    DefaultTableModel dtm = (DefaultTableModel) jtableventas.getModel();
                    int a = jtableventas.getRowCount()-1;
                    for(int i = a; i >= 0; i--){
                        dtm.removeRow(dtm.getRowCount()-1);
                    }
                    jtxtcambio.setText("0.00");
                    jtxttotal.setText("0.00");
                }else{
                    Instancias._ventas = null;
                    this.dispose();
                }
            }else{
                btnaniadir.setEnabled(true);
                btnaniadir.setEnabled(true);
                this.btneliminar.setEnabled(true);
                this.btnsaldar.setEnabled(true);
                this.btncancelar.setEnabled(true);
                this.btnnuevo.setEnabled(false);
                btnmiscelaneos.setEnabled(true);
                ven.btn_nuevo(jtxtidventa);
                DefaultTableModel dtm = (DefaultTableModel) jtableventas.getModel();
                int a = jtableventas.getRowCount()-1;
                for(int i = a; i >= 0; i--){
                    dtm.removeRow(dtm.getRowCount()-1);
                }
                jtxtcambio.setText("0.00");
                jtxttotal.setText("0.00");
            }         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) jtableventas.getModel();
        int a = jtableventas.getRowCount()-1;
        for(int i = a; i >= 0; i--){
            dtm.removeRow(dtm.getRowCount()-1);
        }
        jtxtcambio.setText("0.00");
        jtxttotal.setText("0.00");
        jtxtidventa.setText("");
        btnaniadir.setEnabled(false);
        btnsaldar.setEnabled(false);
        btneliminar.setEnabled(false);
        btnmiscelaneos.setEnabled(false);
        btnnuevo.setEnabled(true);
        
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
    
        int row = jtableventas.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel)jtableventas.getModel();
        modelo.removeRow(row);

        double t = 0;
        double p = 0;

        if(jtableventas.getRowCount() > 0){
            for(int i = 0; i < jtableventas.getRowCount(); i++){
                p = Double.parseDouble(jtableventas.getValueAt(i, 3).toString());
                t += p;
            }
            jtxttotal.setText(String.valueOf(t));
            ven.obtenCantidadActual(Integer.parseInt(jtableventas.getValueAt(jtableventas.getSelectedRow(), 0).toString()));
        }   ven.sumaProducto(Integer.parseInt(jtableventas.getValueAt(jtableventas.getSelectedRow(), 0).toString()));
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnsaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaldarActionPerformed
        
        String pago;
        if(forma_pago.equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado forma de pago");
        }else{
            pago = JOptionPane.showInputDialog(this, "¿Cantidad monetaria?", "FENIX POS", JOptionPane.QUESTION_MESSAGE);
            
            if(pago.equals("")){
                jtm.jTextAreaMessage("No se introdujo cantidad de monetaria");
            }if(Double.parseDouble(pago) < Double.parseDouble(jtxttotal.getText())){
                Object[] opciones = {"Aceptar","Cancelar"};
                int mensaje = JOptionPane.showOptionDialog(null, "La cantidad monetaria es menor al total,"
                        + "\n¿Aún así desea saldar la cuenta?", "Fenix POS[Aviso]", 
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, 
                        null, opciones, opciones[0]);
                if(mensaje == JOptionPane.OK_OPTION){
                    double _pago = Double.parseDouble(pago);
                    ven.btn_guardarVenta(forma_pago, 
                            jtxtfecha.getText(), 
                            jtxthora.getText(), 
                            Menu.idusu, 
                            Menu.idcompania);
                    for(int row = 0; row < jtableventas.getRowCount(); row++){
                        ven.jbguardarventaproducto(Integer.parseInt(jtxtidventa.getText()), 
                                Integer.parseInt(jtableventas.getValueAt(row, 0).toString()),
                                jtableventas.getValueAt(row, 2).toString(),
                                Double.parseDouble(jtableventas.getValueAt(row, 3).toString()),
                                Menu.idusu,
                                Menu.idcompania);
                    }

                    double cambio = _pago - Double.parseDouble(jtxttotal.getText());                      
                    ven.jbguardartotales(Integer.parseInt(jtxtidventa.getText()), 
                            Double.parseDouble(jtxttotal.getText()), _pago, cambio,
                            Menu.idusu,
                            Menu.idcompania);                    
                    jtxtcambio.setText(String.valueOf(cambio));                    
                    btnaniadir.setEnabled(false);
                    btnsaldar.setEnabled(false);
                    btnnuevo.setEnabled(true);
                    btnmiscelaneos.setEnabled(false);
                    btneliminar.setEnabled(false);
                    ven.mostrarVentas(ConsultaVentas.jtventas, "", "");  
                    ven.muestraTotales(ConsultaVentas.jttotales);                    
                    jtm.jTextAreaMessageCambio(
                            "\n Venta: "+jtxttotal.getText(),
                            "\n Pago: "+_pago,
                            "\n Cambio: "+cambio,                            
                            "\n Venta Saldada");
                }
            }else{
                System.out.println("Usuario id: "+Menu.idusu);
                double _pago = Double.parseDouble(pago);
                    ven.btn_guardarVenta(forma_pago, 
                            jtxtfecha.getText(), 
                            jtxthora.getText(), 
                            Menu.idusu, 
                            Menu.idcompania);
                    for(int row = 0; row < jtableventas.getRowCount(); row++){
                        ven.jbguardarventaproducto(Integer.parseInt(jtxtidventa.getText()), 
                                Integer.parseInt(jtableventas.getValueAt(row, 0).toString()),
                                jtableventas.getValueAt(row, 2).toString(),
                                Double.parseDouble(jtableventas.getValueAt(row, 3).toString()),
                                Menu.idusu,
                                Menu.idcompania);
                    }                                        
                    double cambio = _pago - Double.parseDouble(jtxttotal.getText());                    
                    ven.jbguardartotales(Integer.parseInt(jtxtidventa.getText()), 
                            Double.parseDouble(jtxttotal.getText()), 
                            _pago, 
                            cambio,
                            Menu.idusu,
                            Menu.idcompania);
                    jtxtcambio.setText(String.valueOf(cambio));       
                    btnaniadir.setEnabled(false);
                    btnsaldar.setEnabled(false);
                    btnnuevo.setEnabled(true);
                    btnmiscelaneos.setEnabled(false);
                    btneliminar.setEnabled(false);
                    ven.mostrarVentas(ConsultaVentas.jtventas, "", "");  
                    ven.muestraTotales(ConsultaVentas.jttotales);
                    jtm.jTextAreaMessageCambio(
                            "\n Venta: "+jtxttotal.getText(),
                            "\n Pago: "+_pago,
                            "\n Cambio: "+cambio,                            
                            "\n Venta Saldada");
            }            
        }       
        
    }//GEN-LAST:event_btnsaldarActionPerformed

    private void jrefectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrefectivoActionPerformed

        forma_pago = "Efectivo";
        
    }//GEN-LAST:event_jrefectivoActionPerformed

    private void jrtarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrtarjetaActionPerformed

        forma_pago = "Tarjeta";
        
    }//GEN-LAST:event_jrtarjetaActionPerformed

    private void btnmiscelaneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmiscelaneosActionPerformed

        ListaProductos.whoisselected = "ventasmiscelaneas";
        inst.getInstaciaVentasMiscelaneas();        
        
    }//GEN-LAST:event_btnmiscelaneosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._ventas = null;
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnaniadir;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    public static javax.swing.JButton btnmiscelaneos;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsaldar;
    private javax.swing.JButton btnsalir;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrefectivo;
    private javax.swing.JRadioButton jrtarjeta;
    public static javax.swing.JTable jtableventas;
    private javax.swing.JTextField jtxtcambio;
    public static javax.swing.JTextField jtxtfecha;
    private javax.swing.JTextField jtxthora;
    private javax.swing.JTextField jtxtidventa;
    public static javax.swing.JTextField jtxttotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
    
    public class cronometro implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent evt)
        {
            GregorianCalendar tiempo=new GregorianCalendar();
            int dia, mes, anio, hora, minutos, segundos;
            dia=tiempo.get(Calendar.DAY_OF_MONTH);            dia=tiempo.get(Calendar.DAY_OF_MONTH);
            mes=tiempo.get(Calendar.MONTH)+1;
            anio=tiempo.get(Calendar.YEAR);
            hora=tiempo.get(Calendar.HOUR);
            minutos=tiempo.get(Calendar.MINUTE);
            segundos=tiempo.get(Calendar.SECOND);
                  
            jtxtfecha.setText(anio+"-"+mes+"-"+dia);
            jtxthora.setText(hora+":"+minutos+":"+segundos);                     
        }  
    }
}
