/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Productos;

import Frames.Listados.ListaProveedores;
import Frames.Listados.ListaCategorias;
import C.Funciones.BuscarImagen;
import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import C.Productos.productos;
import C.Proveedores.proveedores;
import Frames.Menu;
import ReportesJasper.reportes;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author jraraujo
 */
public class Productos extends javax.swing.JFrame {
    File archivo;
    JFileChooser SelectArchivo=new JFileChooser();
    JTextAreaMessages jtm = new JTextAreaMessages();
    productos pro = new productos();
    proveedores prov = new proveedores();
    int idproducto, idproveedor, idcategoria;
    String producto, descripcion, unidad, proveedor, marca, precio, 
            fecha, nombreimagen, direccionimagen;
    Border border, margin;
    JLabel jtxtfecha = new JLabel();    
    Image img;
    public static int id;
    public static String whoisselected;
    BuscarImagen bi = new BuscarImagen();
    reportes rep = new reportes();
    Instancias inst = new Instancias();
    CheckAccess cha = new CheckAccess();
    JTableHeader th;
    String _estatus = "Habilitado";
    
    /**
     * Creates new form Productos
     * @throws java.lang.ClassNotFoundException
     */
    public Productos() throws ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        //jtproductos.setDefaultEditor(Object.class, null);
        th = jtproductos.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        cha.revisarAccesosProductos(Menu.idusu);
        pro.muestraRegistros(jtproductos, "", Menu.idcompania);
        jchkestatus.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jbmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbdeshabilitados = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jtxtbuscar = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jtxtbusproveedor = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jbsalir = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtproductos = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jpregistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtproducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtdescripcion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcmbunidad = new javax.swing.JComboBox<>();
        jbproveedor = new javax.swing.JButton();
        jtxtidproveedor = new javax.swing.JTextField();
        jtxtproveedor = new javax.swing.JTextField();
        jbcategoria = new javax.swing.JButton();
        jtxtcategoria = new javax.swing.JTextField();
        jdtcfecha = new com.toedter.calendar.JDateChooser();
        jtxtmarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtprecio = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtxtcantmax = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtcantmin = new javax.swing.JTextField();
        jchkestatus = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmacciones = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmreportes = new javax.swing.JMenu();
        jmi_reporte = new javax.swing.JMenuItem();
        jmi_repprodalm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari [Registro de Productos]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setEnabled(false);
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator1);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setEnabled(false);
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator2);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setEnabled(false);
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator8);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setBorder(null);
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.setEnabled(false);
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator3);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setToolTipText("");
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setEnabled(false);
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator4);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setBorder(null);
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setEnabled(false);
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreporteActionPerformed(evt);
            }
        });
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator5);

        jbdeshabilitados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/downpro.png"))); // NOI18N
        jbdeshabilitados.setBorder(null);
        jbdeshabilitados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbdeshabilitados.setEnabled(false);
        jbdeshabilitados.setFocusable(false);
        jbdeshabilitados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbdeshabilitados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbdeshabilitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeshabilitadosActionPerformed(evt);
            }
        });
        jToolBar1.add(jbdeshabilitados);
        jToolBar1.add(jSeparator10);

        jLabel4.setText("Buscar:");
        jToolBar1.add(jLabel4);
        jToolBar1.add(jSeparator12);

        jtxtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbuscarKeyReleased(evt);
            }
        });
        jToolBar1.add(jtxtbuscar);
        jToolBar1.add(jSeparator11);

        jLabel7.setText("Buscar por proveedor:");
        jToolBar1.add(jLabel7);
        jToolBar1.add(jSeparator6);

        jtxtbusproveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbusproveedorKeyReleased(evt);
            }
        });
        jToolBar1.add(jtxtbusproveedor);
        jToolBar1.add(jSeparator13);

        jbsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jbsalir.setBorder(null);
        jbsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbsalir.setFocusable(false);
        jbsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbsalir);
        jToolBar1.add(jSeparator7);

        jtproductos.setAutoCreateRowSorter(true);
        jtproductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtproductos.setForeground(new java.awt.Color(0, 153, 153));
        jtproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Producto", "Descripción", "Unidad", "Id Proveedor", "Proveedor", "Marca", "Precio", "Fecha", "Id Categoria", "Cant. Max.", "Cant. Min."
            }
        ));
        jtproductos.setEnabled(false);
        jtproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtproductosMouseClicked(evt);
            }
        });
        jtproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtproductosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtproductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(Color.decode("#C70039"));

        jpregistro.setBackground(Color.decode("#C70039"));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Producto:");

        jScrollPane1.setViewportView(jtxtdescripcion);

        jtxtdescripcion.setColumns(20);
        jtxtdescripcion.setLineWrap(true);
        jtxtdescripcion.setRows(5);
        jtxtdescripcion.setWrapStyleWord(true);
        jtxtdescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        jScrollPane1.setViewportView(jtxtdescripcion);

        javax.swing.GroupLayout jpregistroLayout = new javax.swing.GroupLayout(jpregistro);
        jpregistro.setLayout(jpregistroLayout);
        jpregistroLayout.setHorizontalGroup(
            jpregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpregistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(jpregistroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtproducto)))
                .addContainerGap())
        );
        jpregistroLayout.setVerticalGroup(
            jpregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpregistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jpregistro);

        jPanel1.setBackground(Color.decode("#C70039")
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Unidad:");

        jcmbunidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Pz", "Kg" }));

        jbproveedor.setText("Proveedor:");
        jbproveedor.setEnabled(false);
        jbproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbproveedorActionPerformed(evt);
            }
        });

        jtxtidproveedor.setEditable(false);

        jtxtproveedor.setEditable(false);

        jbcategoria.setText("Categoria:");
        jbcategoria.setEnabled(false);
        jbcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcategoriaActionPerformed(evt);
            }
        });

        jtxtcategoria.setEditable(false);

        jdtcfecha.setDateFormatString("yyyy-MM-dd");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Marca:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Precio sugerido:");

        jtxtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtprecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtmarca)
                            .addComponent(jtxtprecio)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(6, 6, 6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                            .addComponent(jdtcfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtcategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcmbunidad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmbunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbproveedor)
                    .addComponent(jtxtproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jdtcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbcategoria)
                    .addComponent(jtxtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);

        jPanel7.setOpaque(false);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cantidad Max:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cantidad Min:");

        jchkestatus.setText("Habilitado");
        jchkestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkestatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jchkestatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtcantmin)
                            .addComponent(jtxtcantmax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtcantmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtcantmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchkestatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7);

        jTabbedPane1.addTab("Alta de Productos", jPanel2);

        jMenuBar2.setBackground(Color.decode("#A80030"));

        jmacciones.setForeground(new java.awt.Color(255, 255, 255));
        jmacciones.setText("Acciones");
        jmacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmacciones.setEnabled(false);

        jmi_guardar.setText("Guardar");
        jmi_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_guardar.setEnabled(false);
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_cancelar.setEnabled(false);
        jmi_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cancelarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_cancelar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_eliminar.setEnabled(false);
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_eliminar);

        jmi_modificar.setText("Modificar");
        jmi_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_modificar.setEnabled(false);
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_modificar);

        jmi_exportar.setText("Exportar");
        jmi_exportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmi_exportar.setEnabled(false);
        jmi_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_exportarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_exportar);
        jmacciones.add(jSeparator9);

        jMenuItem2.setText("Salir");
        jmacciones.add(jMenuItem2);

        jMenuBar2.add(jmacciones);

        jmreportes.setForeground(new java.awt.Color(255, 255, 255));
        jmreportes.setText("Reportes");
        jmreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmreportes.setEnabled(false);

        jmi_reporte.setText("Reporte Productos");
        jmi_reporte.setEnabled(false);
        jmi_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reporteActionPerformed(evt);
            }
        });
        jmreportes.add(jmi_reporte);

        jmi_repprodalm.setText("Reporte Productos por Almacenes");
        jmi_repprodalm.setEnabled(false);
        jmi_repprodalm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_repprodalmActionPerformed(evt);
            }
        });
        jmreportes.add(jmi_repprodalm);

        jMenuBar2.add(jmreportes);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproveedorActionPerformed

        jbproveedor.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                ListaProveedores.whosSelected = jbproveedor;
            }
            
            @Override
            public void mousePressed(MouseEvent e) {
                
            }
            
            @Override
            public void mouseReleased(MouseEvent e) {
                
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                
            }
            
        });
        inst.getInstanciaListaProveedores();
        
    }//GEN-LAST:event_jbproveedorActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed

        Instancias._productos = null;
        this.dispose();
        
    }//GEN-LAST:event_jbsalirActionPerformed

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed

        if(jtxtproducto.getText().equals("") || jcmbunidad.getSelectedItem().toString().equals("") 
                || jtxtidproveedor.getText().equals("") || jtxtmarca.getText().equals("") 
                || jtxtprecio.getText().equals("") || jtxtcategoria.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            pro.jbguardar(jtxtproducto.getText(),
                jtxtdescripcion.getText(),
                jcmbunidad.getSelectedItem().toString(),
                Integer.parseInt(jtxtidproveedor.getText()),
                jtxtproveedor.getText(),
                jtxtmarca.getText(),
                Double.parseDouble(jtxtprecio.getText()),
                jdtcfecha,
                Integer.parseInt(jtxtcategoria.getText()),
                Integer.parseInt(jtxtcantmax.getText()),
                Integer.parseInt(jtxtcantmin.getText()),
                _estatus,
                Menu.idusu,
                Menu.idcompania);
            pro.muestraRegistros(jtproductos, "", Menu.idcompania);
            pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
        }
        
    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jtproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtproductosMouseClicked
        
        try {            
            
            idproducto = Integer.parseInt(jtproductos.getValueAt(jtproductos.getSelectedRow(), 0).toString());
            jtxtproducto.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 1).toString());
            jtxtdescripcion.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 2).toString());
            jcmbunidad.setSelectedItem(jtproductos.getValueAt(jtproductos.getSelectedRow(), 3).toString());
            jtxtidproveedor.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 4).toString());
            jtxtproveedor.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 5).toString());
            jtxtmarca.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 6).toString());
            jtxtprecio.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 7).toString());
            fecha = jtproductos.getValueAt(jtproductos.getSelectedRow(), 8).toString();   
            DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
            Date date1 = df1.parse(fecha);
            jdtcfecha.setDate(date1); 
            jtxtcategoria.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 9).toString());
            jtxtcantmax.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 10).toString());
            jtxtcantmin.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 11).toString()); 
            _estatus = jtproductos.getValueAt(jtproductos.getSelectedRow(), 12).toString();
            if(!_estatus.equals("")){
                jchkestatus.setSelected(true);
            }
          
        } catch (ParseException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jtproductosMouseClicked

    private void jtxtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtprecioActionPerformed

    private void jmi_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cancelarActionPerformed

       pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
       pro.mostrarCompras(jtproductos);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_cancelarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed

         if(String.valueOf(idproducto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            pro.jbeliminar(idproducto);
            pro.muestraRegistros(jtproductos, "", Menu.idcompania);
             pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
        }
                
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed

        if(String.valueOf(idproducto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            if(jtxtproducto.getText().equals("") || jcmbunidad.getSelectedItem().toString().equals("") 
                || jtxtidproveedor.getText().equals("") || jtxtmarca.getText().equals("") 
                || jtxtprecio.getText().equals("") || jtxtcategoria.getText().equals("")){
                
                jtm.jTextAreaMessage("Existen campos vacios");
            }else{
                
                pro.jbmodificar(jtxtproducto.getText(), 
                jtxtdescripcion.getText(), 
                jcmbunidad.getSelectedItem().toString(),
                Integer.parseInt(jtxtidproveedor.getText()),
                jtxtproveedor.getText(), 
                jtxtmarca.getText(),
                Double.parseDouble(jtxtprecio.getText()),
                jdtcfecha,          
                Integer.parseInt(jtxtcategoria.getText()),                            
                Integer.parseInt(jtxtcantmax.getText()),
                Integer.parseInt(jtxtcantmin.getText()),
                _estatus,
                Menu.idusu,
                Menu.idcompania,
                idproducto);              
                pro.muestraRegistros(jtproductos, "", Menu.idcompania);
                pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
            }
        }
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jmi_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_exportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();        
        fexpex.exportarExcel(jtproductos);
        
    }//GEN-LAST:event_jmi_exportarActionPerformed

    private void jbcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcategoriaActionPerformed

        try {
            ListaCategorias lc = new ListaCategorias();
            lc.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbcategoriaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._productos = null;
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jtxtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbuscarKeyReleased

        pro.muestraRegistros(jtproductos, jtxtbuscar.getText(), Menu.idcompania);
        
    }//GEN-LAST:event_jtxtbuscarKeyReleased

    private void jmi_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reporteActionPerformed

        try {
            rep.EmisionReporteDeProductos("/ReportesJasper/", "ReporteDeProductos.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmi_reporteActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();        
        fexpex.exportarExcel(jtproductos);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        if(String.valueOf(idproducto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            if(jtxtproducto.getText().equals("") || jcmbunidad.getSelectedItem().toString().equals("") 
                || jtxtidproveedor.getText().equals("") || jtxtmarca.getText().equals("") 
                || jtxtprecio.getText().equals("") || jtxtcategoria.getText().equals("")){
                
                jtm.jTextAreaMessage("Existen campos vacios");
            }else{
                
                pro.jbmodificar(jtxtproducto.getText(), 
                jtxtdescripcion.getText(), 
                jcmbunidad.getSelectedItem().toString(),
                Integer.parseInt(jtxtidproveedor.getText()),
                jtxtproveedor.getText(), 
                jtxtmarca.getText(),
                Double.parseDouble(jtxtprecio.getText()),
                jdtcfecha,          
                Integer.parseInt(jtxtcategoria.getText()),                            
                Integer.parseInt(jtxtcantmax.getText()),
                Integer.parseInt(jtxtcantmin.getText()),
                _estatus,
                Menu.idusu,
                Menu.idcompania,
                idproducto);              
                pro.muestraRegistros(jtproductos, "", Menu.idcompania);
                pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
            }
        }
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

         if(String.valueOf(idproducto).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            pro.jbeliminar(idproducto);
            pro.muestraRegistros(jtproductos, "", Menu.idcompania);
            pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
        }
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

         pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
         pro.muestraRegistros(jtproductos, "", Menu.idcompania);
        
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        if(jtxtproducto.getText().equals("") || jcmbunidad.getSelectedItem().toString().equals("") 
                || jtxtidproveedor.getText().equals("") || jtxtmarca.getText().equals("") 
                || jtxtprecio.getText().equals("") || jtxtcategoria.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
        }else{
            pro.jbguardar(jtxtproducto.getText(),
                jtxtdescripcion.getText(),
                jcmbunidad.getSelectedItem().toString(),
                Integer.parseInt(jtxtidproveedor.getText()),
                jtxtproveedor.getText(),
                jtxtmarca.getText(),
                Double.parseDouble(jtxtprecio.getText()),
                jdtcfecha,
                Integer.parseInt(jtxtcategoria.getText()),
                Integer.parseInt(jtxtcantmax.getText()),
                Integer.parseInt(jtxtcantmin.getText()),
                _estatus,
                Menu.idusu,
                Menu.idcompania);
            pro.muestraRegistros(jtproductos, "", Menu.idcompania);
            pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreporteActionPerformed

        inst.getInstanciasReportesProductos();
        
    }//GEN-LAST:event_jbreporteActionPerformed

    private void jmi_repprodalmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_repprodalmActionPerformed

        try {
            rep.EmisionReporteDeProductosPorAlmacen("/ReportesJasper/", "ReporteDeProductosPorAlmacen.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmi_repprodalmActionPerformed

    private void jtproductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtproductosKeyReleased
        jtproductos.setSurrendersFocusOnKeystroke(true);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){            
            pro.jbmodificar(jtproductos.getValueAt(jtproductos.getSelectedRow(), 1).toString(),
                    jtproductos.getValueAt(jtproductos.getSelectedRow(), 2).toString(),
                    jtproductos.getValueAt(jtproductos.getSelectedRow(), 3).toString(),
                    Integer.parseInt(jtproductos.getValueAt(jtproductos.getSelectedRow(), 4).toString()),
                    jtproductos.getValueAt(jtproductos.getSelectedRow(), 5).toString(),
                    jtproductos.getValueAt(jtproductos.getSelectedRow(), 6).toString(),
                    Double.parseDouble(jtproductos.getValueAt(jtproductos.getSelectedRow(), 7).toString()),
                    jdtcfecha,
                    Integer.parseInt(jtproductos.getValueAt(jtproductos.getSelectedRow(), 9).toString()),
                    Integer.parseInt(jtproductos.getValueAt(jtproductos.getSelectedRow(), 10).toString()),
                    Integer.parseInt(jtproductos.getValueAt(jtproductos.getSelectedRow(), 11).toString()),
                    _estatus,
                    Menu.idusu,
                    Menu.idcompania,
                    Integer.parseInt(jtproductos.getValueAt(jtproductos.getSelectedRow(), 0).toString()));
            pro.muestraRegistros(jtproductos, "", Menu.idcompania);
            pro.limpiar(jtxtproducto, jtxtdescripcion, jcmbunidad, jtxtidproveedor, jtxtproveedor,
                    jtxtmarca, jtxtprecio, jdtcfecha, jtxtfecha, jtxtcategoria, jtxtcantmax, jtxtcantmin);
        }
                    
    }//GEN-LAST:event_jtproductosKeyReleased

    private void jchkestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkestatusActionPerformed

        if(jchkestatus.isSelected() == true){
            _estatus = "Habilitado";
        }else if(jchkestatus.isSelected() == false){
            _estatus = "Deshabilitado";
        }
        
    }//GEN-LAST:event_jchkestatusActionPerformed

    private void jbdeshabilitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeshabilitadosActionPerformed

        inst.getInstanciasProductosDeshabilitados();
        
    }//GEN-LAST:event_jbdeshabilitadosActionPerformed

    private void jtxtbusproveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbusproveedorKeyReleased

        pro.buscarProveedor(jtproductos, jtxtbusproveedor.getText(), Menu.idcompania);        
        
    }//GEN-LAST:event_jtxtbusproveedorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Productos().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbcategoria;
    public static javax.swing.JButton jbdeshabilitados;
    public static javax.swing.JButton jbeliminar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jbmodificar;
    public static javax.swing.JButton jbproveedor;
    public static javax.swing.JButton jbreporte;
    private javax.swing.JButton jbsalir;
    private javax.swing.JCheckBox jchkestatus;
    private javax.swing.JComboBox<String> jcmbunidad;
    private com.toedter.calendar.JDateChooser jdtcfecha;
    public static javax.swing.JMenu jmacciones;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_eliminar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenuItem jmi_modificar;
    public static javax.swing.JMenuItem jmi_reporte;
    public static javax.swing.JMenuItem jmi_repprodalm;
    public static javax.swing.JMenu jmreportes;
    private javax.swing.JPanel jpregistro;
    public static javax.swing.JTable jtproductos;
    private javax.swing.JTextField jtxtbuscar;
    private javax.swing.JTextField jtxtbusproveedor;
    private javax.swing.JTextField jtxtcantmax;
    private javax.swing.JTextField jtxtcantmin;
    public static javax.swing.JTextField jtxtcategoria;
    private javax.swing.JTextArea jtxtdescripcion;
    public static javax.swing.JTextField jtxtidproveedor;
    private javax.swing.JTextField jtxtmarca;
    private javax.swing.JTextField jtxtprecio;
    private javax.swing.JTextField jtxtproducto;
    public static javax.swing.JTextField jtxtproveedor;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    } 
    
}
