/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.MateriaPrima;

import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import Frames.Menu;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.border.Border;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Roman Araujo
 */
public class MateriaPrima extends javax.swing.JFrame {

    Border border, margin;    
    File archivo;
    JFileChooser SelectArchivo;
    C.MateriaPrima.materiaprima mat = new C.MateriaPrima.materiaprima();
    Instancias inst = new Instancias();
    JTextAreaMessages jtm = new JTextAreaMessages();
    CheckAccess cha = new CheckAccess();
    JTableHeader th;
    String path = "";
    URL url = null;
    ImageIcon icon;
    Image img;
    int idmateria;
    
    /**
     * Creates new form MateriaPrima
     */
    public MateriaPrima() {
        initComponents();
        this.setLocationRelativeTo(null);
        jtmateria.setDefaultEditor(Object.class, null);
        th = jtmateria.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        cha.revisarAccesosProveedores(Menu.idusu);
        mat.mostrar(jtmateria, "");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator9 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jbmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbreporte = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        jtxtbuscar = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jbsalir = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtdescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jtxtfecha = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jtxtalmacen = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jtxtpasillo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtxtanaquel = new javax.swing.JTextField();
        jtxtbin = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtmateria = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiguardar = new javax.swing.JMenuItem();
        jmicancelar = new javax.swing.JMenuItem();
        jmieliminar = new javax.swing.JMenuItem();
        jmimodificar = new javax.swing.JMenuItem();
        jmiexportar = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jmisalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmireporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator6);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator5);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator4);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator3);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator2);

        jbreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreporte.setFocusable(false);
        jbreporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbreporte);
        jToolBar1.add(jSeparator1);

        jLabel3.setText("Buscar:");
        jToolBar1.add(jLabel3);

        jtxtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbuscarKeyReleased(evt);
            }
        });
        jToolBar1.add(jtxtbuscar);
        jToolBar1.add(jSeparator8);

        jbsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jbsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbsalir.setFocusable(false);
        jbsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbsalir);
        jToolBar1.add(jSeparator10);

        jLabel1.setText("Nombre:");

        jtxtdescripcion.setColumns(20);
        jtxtdescripcion.setLineWrap(true);
        jtxtdescripcion.setRows(5);
        jtxtdescripcion.setWrapStyleWord(true);
        jtxtdescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        jScrollPane1.setViewportView(jtxtdescripcion);

        jLabel2.setText("Fecha registro:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtxtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jButton1.setText("Almacen:");

        jButton2.setText("Pasillo:");

        jButton3.setText("Anaquel:");

        jButton4.setText("Bin:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtalmacen)
                            .addComponent(jtxtpasillo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtanaquel)
                            .addComponent(jtxtbin))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jtxtalmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jtxtpasillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jtxtanaquel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jtxtbin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jTabbedPane1.addTab("Materia Prima", jPanel1);

        jtmateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdMateriaPrima", "Nombre", "Descripción", "Fecha Registro", "Id Almacen", "Id Pasillo", "Id Anaquel", "Id Bin"
            }
        ));
        jtmateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtmateriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtmateria);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(Color.decode("#C70039"));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Acciones");

        jmiguardar.setText("Guardar");
        jmiguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiguardarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiguardar);

        jmicancelar.setText("Cancelar");
        jmicancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmicancelarActionPerformed(evt);
            }
        });
        jMenu1.add(jmicancelar);

        jmieliminar.setText("Eliminar");
        jmieliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmieliminarActionPerformed(evt);
            }
        });
        jMenu1.add(jmieliminar);

        jmimodificar.setText("Modificar");
        jmimodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmimodificarActionPerformed(evt);
            }
        });
        jMenu1.add(jmimodificar);

        jmiexportar.setText("Exportar");
        jmiexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiexportarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiexportar);
        jMenu1.add(jSeparator7);

        jmisalir.setText("Salir");
        jmisalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmisalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmisalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Reporte");

        jmireporte.setText("Reporte");
        jMenu2.add(jmireporte);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiguardarActionPerformed

        if(jtxtnombre.getText().equals("") || jtxtalmacen.getText().equals("") 
                || jtxtpasillo.getText().equals("") || jtxtanaquel.getText().equals("")
                || jtxtbin.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
            
        }else{
            mat.guardar(jtxtnombre.getText(), jtxtdescripcion.getText(), jtxtfecha, 
                    Integer.parseInt(jtxtalmacen.getText()), 
                    Integer.parseInt(jtxtpasillo.getText()), 
                    Integer.parseInt(jtxtanaquel.getText()), 
                    Integer.parseInt(jtxtbin.getText()), Menu.idusu, Menu.idcompania);
            mat.cancelar(jtxtnombre, jtxtdescripcion, jtxtfecha, jtxtalmacen, jtxtpasillo, jtxtanaquel, jtxtbin);
            mat.mostrar(jtmateria, "");
        }

    }//GEN-LAST:event_jmiguardarActionPerformed

    private void jmicancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmicancelarActionPerformed

        mat.cancelar(jtxtnombre, jtxtdescripcion, jtxtfecha, jtxtalmacen, jtxtpasillo, jtxtanaquel, jtxtbin);
        mat.mostrar(jtmateria, "");

    }//GEN-LAST:event_jmicancelarActionPerformed

    private void jmieliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmieliminarActionPerformed

        if(String.valueOf(idmateria).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un identificador");
        }else{
            mat.eliminar(idmateria);
            mat.cancelar(jtxtnombre, jtxtdescripcion, jtxtfecha, jtxtalmacen, jtxtpasillo, jtxtanaquel, jtxtbin);
            mat.mostrar(jtmateria, "");
        }

    }//GEN-LAST:event_jmieliminarActionPerformed

    private void jmimodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmimodificarActionPerformed

        if(jtxtnombre.getText().equals("") || jtxtalmacen.getText().equals("") 
                || jtxtpasillo.getText().equals("") || jtxtanaquel.getText().equals("")
                || jtxtbin.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
            
        }else{
            mat.modificar(jtxtnombre.getText(), 
                    jtxtdescripcion.getText(), 
                    jtxtfecha, 
                    Integer.parseInt(jtxtalmacen.getText()), 
                    Integer.parseInt(jtxtpasillo.getText()), 
                    Integer.parseInt(jtxtanaquel.getText()), 
                    Integer.parseInt(jtxtbin.getText()), 
                    Menu.idusu, 
                    Menu.idcompania);
            mat.cancelar(jtxtnombre, jtxtdescripcion, jtxtfecha, jtxtalmacen, jtxtpasillo, jtxtanaquel, jtxtbin);
            mat.mostrar(jtmateria, "");
        }

    }//GEN-LAST:event_jmimodificarActionPerformed

    private void jmiexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtmateria);

    }//GEN-LAST:event_jmiexportarActionPerformed

    private void jmisalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmisalirActionPerformed

        Instancias._datosempresa = null;
        this.dispose();

    }//GEN-LAST:event_jmisalirActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

    if(jtxtnombre.getText().equals("") || jtxtalmacen.getText().equals("") 
                || jtxtpasillo.getText().equals("") || jtxtanaquel.getText().equals("")
                || jtxtbin.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
            
        }else{
            mat.guardar(jtxtnombre.getText(), jtxtdescripcion.getText(), jtxtfecha, 
                    Integer.parseInt(jtxtalmacen.getText()), 
                    Integer.parseInt(jtxtpasillo.getText()), 
                    Integer.parseInt(jtxtanaquel.getText()), 
                    Integer.parseInt(jtxtbin.getText()), Menu.idusu, Menu.idcompania);
            mat.cancelar(jtxtnombre, jtxtdescripcion, jtxtfecha, jtxtalmacen, jtxtpasillo, jtxtanaquel, jtxtbin);
            mat.mostrar(jtmateria, "");
        }        

    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        mat.cancelar(jtxtnombre, jtxtdescripcion, jtxtfecha, jtxtalmacen, jtxtpasillo, jtxtanaquel, jtxtbin);
        mat.mostrar(jtmateria, "");

    }//GEN-LAST:event_jbcancelarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        if(String.valueOf(idmateria).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado un identificador");
        }else{
            mat.eliminar(idmateria);
            mat.cancelar(jtxtnombre, jtxtdescripcion, jtxtfecha, jtxtalmacen, jtxtpasillo, jtxtanaquel, jtxtbin);
            mat.mostrar(jtmateria, "");
        }

    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

if(jtxtnombre.getText().equals("") || jtxtalmacen.getText().equals("") 
                || jtxtpasillo.getText().equals("") || jtxtanaquel.getText().equals("")
                || jtxtbin.getText().equals("")){
            jtm.jTextAreaMessage("Existen campos vacios");
            
        }else{
            mat.modificar(jtxtnombre.getText(), 
                    jtxtdescripcion.getText(), 
                    jtxtfecha, 
                    Integer.parseInt(jtxtalmacen.getText()), 
                    Integer.parseInt(jtxtpasillo.getText()), 
                    Integer.parseInt(jtxtanaquel.getText()), 
                    Integer.parseInt(jtxtbin.getText()), 
                    Menu.idusu, 
                    Menu.idcompania);
            mat.cancelar(jtxtnombre, jtxtdescripcion, jtxtfecha, jtxtalmacen, jtxtpasillo, jtxtanaquel, jtxtbin);
            mat.mostrar(jtmateria, "");
        }

    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtmateria);

    }//GEN-LAST:event_jbexportarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed

        Instancias._datosempresa = null;
        this.dispose();

    }//GEN-LAST:event_jbsalirActionPerformed

    private void jtmateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtmateriaMouseClicked
        
        idmateria = Integer.parseInt(jtmateria.getValueAt(jtmateria.getSelectedRow(), 0).toString());
        
    }//GEN-LAST:event_jtmateriaMouseClicked

    private void jtxtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbuscarKeyReleased

        mat.mostrar(jtmateria, jtxtbuscar.getText());
        
    }//GEN-LAST:event_jtxtbuscarKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._materiaprima = null;
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MateriaPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbexportar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JButton jbreporte;
    private javax.swing.JButton jbsalir;
    private javax.swing.JMenuItem jmicancelar;
    private javax.swing.JMenuItem jmieliminar;
    private javax.swing.JMenuItem jmiexportar;
    private javax.swing.JMenuItem jmiguardar;
    private javax.swing.JMenuItem jmimodificar;
    private javax.swing.JMenuItem jmireporte;
    private javax.swing.JMenuItem jmisalir;
    private javax.swing.JTable jtmateria;
    private javax.swing.JTextField jtxtalmacen;
    private javax.swing.JTextField jtxtanaquel;
    private javax.swing.JTextField jtxtbin;
    private javax.swing.JTextField jtxtbuscar;
    private javax.swing.JTextArea jtxtdescripcion;
    private com.toedter.calendar.JDateChooser jtxtfecha;
    private javax.swing.JTextField jtxtnombre;
    private javax.swing.JTextField jtxtpasillo;
    // End of variables declaration//GEN-END:variables

    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}
