/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Listados;

import C.Devoluciones.devoluciones;
import C.Funciones.Instancias;
import Frames.Devoluciones.Devoluciones;
import Frames.Menu;
import Frames.MovimientosAlmacen.MovimientosAlmacen;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jraraujo
 */
public class ListarProductos extends javax.swing.JFrame {
    
    C.MovimientosAlmacen.movimientosalmacen movalm = new C.MovimientosAlmacen.movimientosalmacen();
    devoluciones devo = new devoluciones();
    public static String whoisselected;
    JTableHeader th;    

    /**
     * Creates new form ListarProductos
     */
    public ListarProductos() {
        initComponents();
        this.setLocationRelativeTo(null);
        th = jtproductos.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        jtproductos.setDefaultEditor(Object.class, null);
        switch(whoisselected){
            case "devolucionesproducto":
                devo.muestraProductos(jtproductos, 
                        Integer.parseInt(Devoluciones.jtxtidventa.getText()), 
                        Menu.idcompania);
                break;
            case "movimientosproducto":
                movalm.muestraProductos(jtproductos, Menu.idcompania);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtproductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Lista de Productos]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtproductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtproductos.setForeground(new java.awt.Color(0, 102, 102));
        jtproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Id Venta", "Id Producto", "Producto", "Precio Unitario"
            }
        ));
        jtproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtproductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtproductosMouseClicked

        if(whoisselected.equals("movimientosproducto")){
            MovimientosAlmacen.jtxtidproducto.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 0).toString());
            MovimientosAlmacen.jtxtproducto.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 1).toString());
            MovimientosAlmacen.jtxtdescripcion.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 2).toString());
            MovimientosAlmacen.jtxtunidad.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 3).toString());
            Instancias._listarproductos = null;
            this.dispose();
        }else if(whoisselected.equals("devolucionesproducto")){
            Devoluciones.jtxtidproducto.setText(jtproductos.getValueAt(jtproductos.getSelectedRow(), 2).toString());
            Instancias._listarproductos = null;
            this.dispose();
        }
        
    }//GEN-LAST:event_jtproductosMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

       Instancias._listarproductos = null;
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListarProductos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtproductos;
    // End of variables declaration//GEN-END:variables

    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}
