/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Listados;

import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Pasillo.pasillo;
import Frames.Anaqueles.Anaqueles;
import Frames.EntradasProducto.EntradasProducto;
import Frames.Devoluciones.Devoluciones;
import Frames.Menu;
import Frames.MovimientosAlmacen.MovimientosAlmacen;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jraraujo
 */
public class ListarPasillos extends javax.swing.JFrame {
    
    pasillo pas = new pasillo();        
    Instancias inst = new Instancias();
    JTextAreaMessages jtm = new JTextAreaMessages();
    public static String whoisselected;
    JTableHeader th;
    /**
     * Creates new form ListarPasillos
     */
    public ListarPasillos() {
        initComponents();
        this.setLocationRelativeTo(null);
        th = jtpasillos.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        jtpasillos.setDefaultEditor(Object.class, null);
        switch (whoisselected) {
            case "dev_jtxtidpasillo":
                pas.mostrarRegistros(jtpasillos, Integer.parseInt(Devoluciones.jtxtidalmacen.getText()), 
                        0, Menu.idcompania);
                break;
            case "ent_jbidpasillo":
                pas.mostrarRegistros(jtpasillos, Integer.parseInt(EntradasProducto.jtxtidalmacen.getText()),
                        0, Menu.idcompania);
                break;
            case "movimientospasillo":
                pas.mostrarRegistros(jtpasillos, Integer.parseInt(MovimientosAlmacen.jtxtidalmacen.getText()), 
                        0, Menu.idcompania);
                break;
             case "ana_jbidpasillo":
                pas.mostrarRegistros(jtpasillos, 0, 0, Menu.idcompania);
                break;
             case "origen_pasillo":                 
                pas.mostrarRegistros(jtpasillos, 
                    Integer.parseInt(MovimientosAlmacen.jtxtorialmacen.getText()), 
                    Integer.parseInt(MovimientosAlmacen.jtxtidproducto.getText()), 
                    Menu.idcompania);           
                break;
            default:                
                pas.mostrarRegistros(jtpasillos, 0, 0, Menu.idcompania);
                break;

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtpasillos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Lista de Pasillos]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 102));

        jtpasillos.setForeground(new java.awt.Color(0, 102, 102));
        jtpasillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Pasillo", "Descripcion", "Id Almacen"
            }
        ));
        jtpasillos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpasillosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtpasillos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtpasillosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpasillosMouseClicked

        switch (whoisselected) {
            case "dev_jtxtidpasillo":
                Devoluciones.jtxtidpasillo.setText(jtpasillos.getValueAt(jtpasillos.getSelectedRow(), 0).toString());
                Instancias._listarpasillos = null;
                this.dispose();
                break;
            case "ent_jbidpasillo":
                EntradasProducto.jtxtidpasillo.setText(jtpasillos.getValueAt(jtpasillos.getSelectedRow(), 0).toString());
                Instancias._listarpasillos = null;
                this.dispose();
                break;
            case "movimientospasillo":
                MovimientosAlmacen.jtxtidpasillo.setText(jtpasillos.getValueAt(jtpasillos.getSelectedRow(), 0).toString());
                Instancias._listarpasillos = null;
                this.dispose();
                break;  
            case "ana_jbidpasillo":
                Anaqueles.jtxtidpasillo.setText(jtpasillos.getValueAt(jtpasillos.getSelectedRow(), 0).toString());
                Instancias._listarpasillos = null;
                this.dispose();
                break;
            case "origen_pasillo":
                MovimientosAlmacen.jtxtoripasillo.setText(jtpasillos.getValueAt(jtpasillos.getSelectedRow(), 0).toString());
                Instancias._listarpasillos = null;
                this.dispose();
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_jtpasillosMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._listarpasillos = null;
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPasillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListarPasillos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtpasillos;
    // End of variables declaration//GEN-END:variables
   
    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}
