/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Listados;

import C.Bin.bin;
import C.Funciones.Instancias;
import Frames.Bin.Bin;
import Frames.EntradasProducto.EntradasProducto;
import Frames.Devoluciones.Devoluciones;
import Frames.Menu;
import Frames.MovimientosAlmacen.MovimientosAlmacen;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jraraujo
 */
public class ListarBins extends javax.swing.JFrame {

    bin bin = new bin();
    public static String whoisselected;
    JTableHeader th;
    /**
     * Creates new form ListarBins
     */
    public ListarBins() {
        initComponents();
        this.setLocationRelativeTo(null);    
        th = jtbins.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        jtbins.setDefaultEditor(Object.class, null);
        switch (whoisselected) {
            case "dev_jtxtidbin":
                bin.mostrarRegistros(jtbins, 
                        Integer.parseInt(Devoluciones.jtxtidanaquel.getText()), 
                        0, Menu.idcompania);
                break;
            case "ent_idbin":
                bin.mostrarRegistros(jtbins, 
                        Integer.parseInt(EntradasProducto.jtxtidanaquel.getText()), 
                        0, Menu.idcompania);
                break;
            case "movimientosbin":
                bin.mostrarRegistros(jtbins, Integer.parseInt(MovimientosAlmacen.jtxtidanaquel.getText()), 
                        0, Menu.idcompania);
                break;
            case "bin_jbidanaquel":
                bin.mostrarRegistros(jtbins, Integer.parseInt(Bin.jtxtidanaquel.getText()), 
                        0, Menu.idcompania);
                break;
            case "origen_bin":
                bin.mostrarRegistros(jtbins, Integer.parseInt(MovimientosAlmacen.jtxtorianaquel.getText()), 
                        Integer.parseInt(MovimientosAlmacen.jtxtidproducto.getText()), 
                        Menu.idcompania);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbins = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari[Lista de Bines]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtbins.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtbins.setForeground(new java.awt.Color(0, 102, 102));
        jtbins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Bin", "Descripción", "Id Anaquel"
            }
        ));
        jtbins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbinsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbins);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbinsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbinsMouseClicked

        switch (whoisselected) {
            case "dev_jtxtidbin":
                Devoluciones.jtxtidbin.setText(jtbins.getValueAt(jtbins.getSelectedRow(), 0).toString());
                Instancias._listarbin = null;
                this.dispose();
                break;
            case "ent_idbin":
                EntradasProducto.jtxtidbin.setText(jtbins.getValueAt(jtbins.getSelectedRow(), 0).toString());
                Instancias._listarbin = null;
                this.dispose();
                break;
            case "movimientosbin":
                MovimientosAlmacen.jtxtidbin.setText(jtbins.getValueAt(jtbins.getSelectedRow(), 0).toString());
                Instancias._listarbin = null;
                this.dispose();
                break;
            case "bin_jbidanaquel":
                Bin.jtxtidanaquel.setText(jtbins.getValueAt(jtbins.getSelectedRow(), 0).toString());
                Instancias._listarbin = null;
                this.dispose();
                break;
            case "origen_bin":
                MovimientosAlmacen.jtxtoribin.setText(jtbins.getValueAt(jtbins.getSelectedRow(), 0).toString());
                Instancias._listarbin = null;
                this.dispose();
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_jtbinsMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._listarbin = null;
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarBins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListarBins().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbins;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
}
