/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Empleados;

import C.Funciones.CheckAccess;
import C.Funciones.Instancias;
import C.Funciones.JTextAreaMessages;
import C.Funciones.f_ExportarExcel;
import Frames.Menu;
import ReportesJasper.reportes;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.border.Border;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author jraraujo
 */
public class Empleados extends javax.swing.JFrame {

    Border border, margin;
    C.Empleados.empleados emp = new C.Empleados.empleados();
    int idempleado, estatus;
    String nombre, paterno, materno, rol, fnacimiento, direccion, telefono, correo, 
            chkestatus, usuario, contrasenia;
    File archivo;
    JFileChooser SelectArchivo;    
    reportes rep = new reportes();
    JTextAreaMessages jtm = new JTextAreaMessages();
    Image img;    
    CheckAccess chk = new CheckAccess();
    JTableHeader th;   
    
    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        jtempleados.setDefaultEditor(Object.class, null);
        th = jtempleados.getTableHeader();
        th.setBackground(Color.decode("#66535A"));
        th.setForeground(Color.WHITE);
        //chk.revisarAccesosEmpleados(Menu.idusu);
        emp.muestraRegistros(jtempleados, "", Menu.idcompania);
        emp.mostrarRoles(jcbrol);
//        if(Menu.rol_login.equals("adm")){
//            Empleados.jbcancelar.setEnabled(true);
//            Empleados.jmacciones.setEnabled(true);
//            Empleados.jmi_cancelar.setEnabled(true);
//            Empleados.jbeliminar.setEnabled(true);
//            Empleados.jmi_eliminar.setEnabled(true);
//            Empleados.jbexportar.setEnabled(true);
//            Empleados.jmi_exportar.setEnabled(true);
//            Empleados.jbguardar.setEnabled(true);
//            Empleados.jmi_guardar.setEnabled(true);
//            Empleados.jbmodificar.setEnabled(true);
//            Empleados.jmi_modificar.setEnabled(true);
//            Empleados.jbreportes.setEnabled(true);   
//            Empleados.jmreportes.setEnabled(true);
//            Empleados.jmi_reporte.setEnabled(true);            
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jbguardar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jbcancelar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jbeliminar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jbmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbexportar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbreportes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel6 = new javax.swing.JLabel();
        jtxtbuscar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jbsalir = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtempleados = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtpaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtmaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdtcnacimiento = new com.toedter.calendar.JDateChooser();
        jtxtdireccion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtxttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbrol = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jtxtestatus = new javax.swing.JTextField();
        jtxtcorreo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jchkestatus = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jtxtusuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtcontrasenia = new javax.swing.JPasswordField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmacciones = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();
        jmi_eliminar = new javax.swing.JMenuItem();
        jmi_modificar = new javax.swing.JMenuItem();
        jmi_exportar = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmreportes = new javax.swing.JMenu();
        jmi_reporte = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Himawari [Registro de Empleados]");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diskette.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setFocusable(false);
        jbguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbguardar);
        jToolBar1.add(jSeparator5);

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setFocusable(false);
        jbcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbcancelarMouseClicked(evt);
            }
        });
        jToolBar1.add(jbcancelar);
        jToolBar1.add(jSeparator4);

        jbeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash.png"))); // NOI18N
        jbeliminar.setBorder(null);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbeliminar.setFocusable(false);
        jbeliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbeliminar);
        jToolBar1.add(jSeparator7);

        jbmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jbmodificar.setBorder(null);
        jbmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbmodificar.setFocusable(false);
        jbmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbmodificar);
        jToolBar1.add(jSeparator3);

        jbexportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        jbexportar.setBorder(null);
        jbexportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexportar.setFocusable(false);
        jbexportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbexportarMouseClicked(evt);
            }
        });
        jbexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexportarActionPerformed(evt);
            }
        });
        jToolBar1.add(jbexportar);
        jToolBar1.add(jSeparator2);

        jbreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/files.png"))); // NOI18N
        jbreportes.setBorder(null);
        jbreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbreportes.setFocusable(false);
        jbreportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbreportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbreportesActionPerformed(evt);
            }
        });
        jToolBar1.add(jbreportes);
        jToolBar1.add(jSeparator1);

        jLabel6.setText("Buscar:");
        jToolBar1.add(jLabel6);

        jtxtbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtxtbuscarMouseReleased(evt);
            }
        });
        jToolBar1.add(jtxtbuscar);
        jToolBar1.add(jSeparator6);

        jbsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        jbsalir.setBorder(null);
        jbsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbsalir.setFocusable(false);
        jbsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });
        jToolBar1.add(jbsalir);
        jToolBar1.add(jSeparator8);

        jtempleados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), Color.decode("#C70039"))); // NOI18N
        jtempleados.setForeground(new java.awt.Color(0, 153, 153));
        jtempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Paterno", "Materno", "F. Nacimiento", "Dirección", "Teléfono", "Correo", "Estatus", "Rol", "Usuario"
            }
        ));
        jtempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtempleadosMouseClicked(evt);
            }
        });
        jtempleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtempleadosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtempleados);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(Color.decode("#C70039"));
        jPanel5.setSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, 157));

        jPanel1.setBackground(Color.decode("#C70039")
        );
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jtxtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Paterno:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Materno:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha de Nacimiento:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");

        jdtcnacimiento.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtnombre)
                            .addComponent(jtxtpaterno)
                            .addComponent(jtxtmaterno, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdtcnacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtdireccion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdtcnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel1);

        jPanel3.setBackground(Color.decode("#C70039")
        );

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Telefono");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Correo:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Rol:");

        jcbrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estatus:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxttelefono)
                            .addComponent(jcbrol, 0, 183, Short.MAX_VALUE)
                            .addComponent(jtxtcorreo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtestatus)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel3);

        jTabbedPane1.addTab("Registro de Empleados y Usuarios", jPanel5);

        jchkestatus.setText("Activo:");
        jchkestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkestatusActionPerformed(evt);
            }
        });

        jLabel11.setText("Usuario:");

        jLabel12.setText("Contraseña:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkestatus)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtcontrasenia)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkestatus)
                    .addComponent(jLabel11)
                    .addComponent(jtxtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtcontrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(Color.decode("#A80030")
        );

        jmacciones.setForeground(new java.awt.Color(255, 255, 255));
        jmacciones.setText("Acciones");

        jmi_guardar.setText("Guardar");
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_guardar);

        jmi_cancelar.setText("Cancelar");
        jmi_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cancelarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_cancelar);

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_eliminar);

        jmi_modificar.setText("Modificar");
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_modificar);

        jmi_exportar.setText("Exportar");
        jmi_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_exportarActionPerformed(evt);
            }
        });
        jmacciones.add(jmi_exportar);
        jmacciones.add(jSeparator9);

        jMenuItem1.setText("Salir");
        jmacciones.add(jMenuItem1);

        jMenuBar2.add(jmacciones);

        jmreportes.setForeground(new java.awt.Color(255, 255, 255));
        jmreportes.setText("Reportes");

        jmi_reporte.setText("Reporte");
        jmi_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reporteActionPerformed(evt);
            }
        });
        jmreportes.add(jmi_reporte);

        jMenuBar2.add(jmreportes);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreActionPerformed

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed

        if(jcbrol.getSelectedItem().toString().equals("--") 
                || jtxtnombre.getText().equals("") 
                || jtxtpaterno.getText().equals("") 
                || jtxtmaterno.getText().equals("")
                || jtxtusuario.getText().equals("")
                || jtxtcontrasenia.getPassword().equals("")){
            jtm.jTextAreaMessage("Información invalida");
        }else{
            char[] contrasenia = jtxtcontrasenia.getPassword();
            String _cont = String.valueOf(contrasenia);
            emp.jbguardar(jtxtnombre.getText(), 
                    jtxtpaterno.getText(), 
                    jtxtmaterno.getText(), 
                    jdtcnacimiento, 
                    jtxtdireccion.getText(), 
                    jtxttelefono.getText(),
                    jtxtcorreo.getText(),
                    estatus,
                    jcbrol.getSelectedItem().toString(),
                    jtxtusuario.getText(),
                    Arrays.toString(jtxtcontrasenia.getPassword()),
                    Menu.idusu,
                    Menu.idcompania);
            emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento, 
                    jtxtdireccion, jtxttelefono, jtxtcorreo, jchkestatus, jcbrol);
            emp.muestraRegistros(jtempleados, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jtempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtempleadosMouseClicked

        try {
            idempleado = Integer.parseInt(jtempleados.getValueAt(jtempleados.getSelectedRow(), 0).toString());
            nombre = jtempleados.getValueAt(jtempleados.getSelectedRow(), 1).toString();
            jtxtnombre.setText(nombre);
            paterno = jtempleados.getValueAt(jtempleados.getSelectedRow(), 2).toString();
            jtxtpaterno.setText(paterno);
            materno = jtempleados.getValueAt(jtempleados.getSelectedRow(), 3).toString();
            jtxtmaterno.setText(materno);
            fnacimiento = jtempleados.getValueAt(jtempleados.getSelectedRow(), 4).toString();
            DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
            Date date1 = df1.parse(fnacimiento);
            jdtcnacimiento.setDate(date1);
            direccion = jtempleados.getValueAt(jtempleados.getSelectedRow(), 5).toString();
            telefono = jtempleados.getValueAt(jtempleados.getSelectedRow(), 6).toString();
            correo = jtempleados.getValueAt(jtempleados.getSelectedRow(), 7).toString();
            chkestatus = jtempleados.getValueAt(jtempleados.getSelectedRow(), 8).toString();
            if(!chkestatus.isEmpty()){
                jchkestatus.setSelected(true);
            }                           
            rol = jtempleados.getValueAt(jtempleados.getSelectedRow(), 9).toString();
            jcbrol.setSelectedItem(rol);
            usuario = jtempleados.getValueAt(jtempleados.getSelectedRow(), 10).toString();
            contrasenia = jtempleados.getValueAt(jtempleados.getSelectedRow(), 11).toString();
            
        } catch (ParseException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jtempleadosMouseClicked

    private void jmi_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cancelarActionPerformed

        emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento, 
                    jtxtdireccion, jtxttelefono, jtxtcorreo, jchkestatus, jcbrol);
        jbguardar.setEnabled(true);
        jbeliminar.setEnabled(false);
        jbmodificar.setEnabled(false);
        jmi_eliminar.setEnabled(false);
        jmi_modificar.setEnabled(false);
        
    }//GEN-LAST:event_jmi_cancelarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed

        Instancias._empleados = null;
        this.dispose();
        
    }//GEN-LAST:event_jbsalirActionPerformed

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed

        if(String.valueOf(idempleado).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date nfecha = sdf.parse(jdtcnacimiento.toString());                
                emp.jbmodificar(nombre,
                        paterno,
                        materno,
                        nfecha,
                        direccion,
                        telefono,
                        correo,
                        estatus,
                        jcbrol.getSelectedItem().toString(),
                        usuario,
                        contrasenia,
                        Menu.idusu,                        
                        Menu.idcompania,
                        idempleado);
                emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento, 
                    jtxtdireccion, jtxttelefono, jtxtcorreo, jchkestatus, jcbrol);
                emp.muestraRegistros(jtempleados, "", Menu.idcompania);
            } catch (ParseException ex) {
                Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed

        if(String.valueOf(idempleado).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            emp.jbeliminar(idempleado, Menu.idcompania);
            emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento, 
                    jtxtdireccion, jtxttelefono, jtxtcorreo, jchkestatus, jcbrol);
            emp.muestraRegistros(jtempleados, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jmi_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_exportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtempleados);
    }//GEN-LAST:event_jmi_exportarActionPerformed


    private void jtxtbuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtbuscarMouseReleased

        emp.muestraRegistros(jtempleados, jtxtbuscar.getText(), Menu.idcompania);
        
    }//GEN-LAST:event_jtxtbuscarMouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        Instancias._empleados = null;
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jbcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbcancelarMouseClicked

        emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento, 
                    jtxtdireccion, jtxttelefono, jtxtcorreo, jchkestatus, jcbrol);
        emp.muestraRegistros(jtempleados, "", Menu.idcompania);
        
    }//GEN-LAST:event_jbcancelarMouseClicked

    private void jbexportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbexportarMouseClicked

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtempleados);
        
    }//GEN-LAST:event_jbexportarMouseClicked

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        if(jcbrol.getSelectedItem().toString().equals("--") 
                || jtxtnombre.getText().equals("") 
                || jtxtpaterno.getText().equals("") 
                || jtxtmaterno.getText().equals("")
                || jtxtusuario.getText().equals("")
                || jtxtcontrasenia.getPassword().equals("")){
            jtm.jTextAreaMessage("Información invalida");
        }else{
            char[] contrasenia = jtxtcontrasenia.getPassword();
            String _cont = String.valueOf(contrasenia);
            emp.jbguardar(jtxtnombre.getText(), 
                    jtxtpaterno.getText(), 
                    jtxtmaterno.getText(), 
                    jdtcnacimiento, 
                    jtxtdireccion.getText(), 
                    jtxttelefono.getText(),
                    jtxtcorreo.getText(),
                    estatus,
                    jcbrol.getSelectedItem().toString(),
                    jtxtusuario.getText(),
                    Arrays.toString(jtxtcontrasenia.getPassword()),
                    Menu.idusu,
                    Menu.idcompania);
            emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento, 
                    jtxtdireccion, jtxttelefono, jtxtcorreo, jchkestatus, jcbrol);
            emp.muestraRegistros(jtempleados, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        if(String.valueOf(idempleado).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date nfecha = sdf.parse(jdtcnacimiento.toString());                
                emp.jbmodificar(nombre,
                        paterno,
                        materno,
                        nfecha,
                        direccion,
                        telefono,
                        correo,
                        estatus,
                        jcbrol.getSelectedItem().toString(),
                        usuario,
                        contrasenia,
                        Menu.idusu,                        
                        Menu.idcompania,
                        idempleado);
                emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento, 
                    jtxtdireccion, jtxttelefono, jtxtcorreo, jchkestatus, jcbrol);
                emp.muestraRegistros(jtempleados, "", Menu.idcompania);
            } catch (ParseException ex) {
                Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        if(String.valueOf(idempleado).equals("")){
            jtm.jTextAreaMessage("No se ha seleccionado registro");
        }else{
            emp.jbeliminar(idempleado, Menu.idcompania);
            emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento, 
                    jtxtdireccion, jtxttelefono, jtxtcorreo, jchkestatus, jcbrol);
            emp.muestraRegistros(jtempleados, "", Menu.idcompania);
        }
        
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jmi_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reporteActionPerformed

        try {
            rep.EmisionReporteDeEmpleados("/ReportesJasper/", "ReporteEmpleados.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jmi_reporteActionPerformed

    private void jbexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexportarActionPerformed

        f_ExportarExcel fexpex = new f_ExportarExcel();
        fexpex.exportarExcel(jtempleados);
        
    }//GEN-LAST:event_jbexportarActionPerformed

    private void jbreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreportesActionPerformed

         try {
            rep.EmisionReporteDeEmpleados("/ReportesJasper/", "ReporteEmpleados.jasper", Menu.idcompania);
        } catch (JRException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbreportesActionPerformed

    private void jtempleadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtempleadosKeyReleased

//        jtempleados.setSurrendersFocusOnKeystroke(true);
//        char[] _cont = jtxtcontrasenia.getPassword();
//        String contrasenia = String.valueOf(_cont);
//        if(String.valueOf(idempleado).equals("")){
//            jtm.jTextAreaMessage("No se ha seleccionado registro");
//        }else{
//            try {
//                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//                java.util.Date nfecha = sdf.parse(jtempleados.getValueAt(jtempleados.getSelectedRow(), 4).toString());
//                java.util.Date rfecha = sdf.parse(jtempleados.getValueAt(jtempleados.getSelectedRow(), 5).toString());
//                emp.jbmodificar(jtempleados.getValueAt(jtempleados.getSelectedRow(), 1).toString(),
//                        jtempleados.getValueAt(jtempleados.getSelectedRow(), 2).toString(),
//                        jtempleados.getValueAt(jtempleados.getSelectedRow(), 3).toString(),
//                        nfecha,
//                        rfecha,
//                        jtempleados.getValueAt(jtempleados.getSelectedRow(), 6).toString(),
//                        contrasenia,
//                        jcbrol.getSelectedItem().toString(),
//                        Menu.idcompania,
//                        idempleado);
//                emp.limpiar(jtxtnombre, jtxtpaterno, jtxtmaterno, jdtcnacimiento,
//                        jdtcregistro, jtxtusuario, jtxtcontrasenia, jcbrol);
//                emp.muestraRegistros(jtempleados, "", Menu.idcompania);
//            } catch (ParseException ex) {
//                Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
        
    }//GEN-LAST:event_jtempleadosKeyReleased

    private void jchkestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkestatusActionPerformed

        if(jchkestatus.isSelected() == true){
            estatus = 1;
        }else if(jchkestatus.isSelected() == false){
            estatus = 0;
        }
        
    }//GEN-LAST:event_jchkestatusActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Empleados().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JButton jbcancelar;
    public static javax.swing.JButton jbeliminar;
    public static javax.swing.JButton jbexportar;
    public static javax.swing.JButton jbguardar;
    public static javax.swing.JButton jbmodificar;
    public static javax.swing.JButton jbreportes;
    private javax.swing.JButton jbsalir;
    private javax.swing.JComboBox<String> jcbrol;
    private javax.swing.JCheckBox jchkestatus;
    private com.toedter.calendar.JDateChooser jdtcnacimiento;
    public static javax.swing.JMenu jmacciones;
    public static javax.swing.JMenuItem jmi_cancelar;
    public static javax.swing.JMenuItem jmi_eliminar;
    public static javax.swing.JMenuItem jmi_exportar;
    public static javax.swing.JMenuItem jmi_guardar;
    public static javax.swing.JMenuItem jmi_modificar;
    public static javax.swing.JMenuItem jmi_reporte;
    public static javax.swing.JMenu jmreportes;
    private javax.swing.JTable jtempleados;
    private javax.swing.JTextField jtxtbuscar;
    private javax.swing.JPasswordField jtxtcontrasenia;
    private javax.swing.JTextField jtxtcorreo;
    private javax.swing.JTextField jtxtdireccion;
    private javax.swing.JTextField jtxtestatus;
    private javax.swing.JTextField jtxtmaterno;
    private javax.swing.JTextField jtxtnombre;
    private javax.swing.JTextField jtxtpaterno;
    private javax.swing.JTextField jtxttelefono;
    private javax.swing.JTextField jtxtusuario;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/usuario.png"));

       return retValue;
    }
    
}
